INSERT INTO iti.airlines (airline_id, airline_name, country, airline_iata, airline_icao, fleet_size, alias) VALUES
(3, '1Time Airline', 'South Africa', '1T', 'RNX', 8, NULL),
(10, '40-Mile Air', 'United States', 'Q5', 'MLA', 4, NULL),
(13, 'Ansett Australia', 'Australia', 'AN', 'AAA', 45, NULL),
(14, 'Abacus International', 'Singapore', '1B', NULL, 0, NULL),
(21, 'Aigle Azur', 'France', 'ZI', 'AAF', 12, NULL),
(22, 'Aloha Airlines', 'United States', 'AQ', 'AAH', 18, NULL),
(24, 'American Airlines', 'United States', 'AA', 'AAL', 875, NULL),
(28, 'Asiana Airlines', 'Republic of Korea', 'OZ', 'AAR', 82, NULL),
(29, 'Askari Aviation', 'Pakistan', '4K', 'AAS', 6, NULL),
(32, 'Afriqiyah Airways', 'Libya', '8U', 'AAW', 13, NULL),
(35, 'Allegiant Air', 'United States', 'G4', 'AAY', 115, NULL),
(42, 'ABSA - Aerolinhas Brasileiras', 'Brazil', 'M3', 'TUS', 9, NULL),
(55, 'Astral Aviation', 'Kenya', '8V', 'ACP', 7, NULL),
(68, 'Air Tindi', 'Canadian Territories', '8T', NULL, 12, NULL),
(72, 'Ada Air', 'Albania', 'ZY', 'ADE', 3, NULL),
(83, 'Adria Airways', 'Slovenia', 'JP', 'ADR', 14, NULL),
(90, 'Air Europa', 'Spain', 'UX', 'AEA', 56, NULL),
(93, 'Aero Benin', 'Benin', 'EM', 'AEB', 4, NULL),
(96, 'Aegean Airlines', 'Greece', 'A3', 'AEE', 65, NULL),
(106, 'Air Europe', 'Italy', 'PE', 'AEL', 8, NULL),
(109, 'Alaska Central Express', 'United States', 'KO', 'AER', 6, NULL),
(110, 'ACES Colombia', 'Colombia', NULL, 'AES', 12, NULL),
(112, 'Astraeus', 'United Kingdom', '5W', 'AEU', 7, NULL),
(114, 'Aerosvit Airlines', 'Ukraine', 'VV', 'AEW', 22, NULL),
(116, 'Air Italy', 'Italy', 'I9', 'AEY', 11, NULL),
(120, 'Alliance Airlines', 'Australia', 'QQ', 'UTY', 28, NULL),
(125, 'Ariana Afghan Airlines', 'Afghanistan', 'FG', 'AFG', 10, NULL),
(130, 'Aeroflot Russian Airlines', 'Russia', 'SU', 'AFL', 255, NULL),
(132, 'Air Bosna', 'Bosnia and Herzegovina', 'JA', 'BON', 5, NULL),
(137, 'Air France', 'France', 'AF', 'AFR', 220, NULL),
(139, 'Air Caledonie International', 'France', 'SB', 'ACI', 6, NULL),
(146, 'Air Salone', 'Sierra Leone', '2O', NULL, 3, NULL),
(149, 'Air Cargo Carriers', 'United States', '2Q', 'SNC', 15, NULL),
(153, 'Air Namibia', 'Namibia', 'SW', 'NMB', 10, NULL),
(165, 'Aerolitoral', 'Mexico', '5D', 'SLI', 35, NULL),
(174, 'Air Glaciers', 'Switzerland', '7T', 'AGV', 8, NULL),
(176, 'Aviogenex', 'Serbia', NULL, 'AGX', 6, NULL),
(179, 'Aeroper', 'Peru', 'PL', 'PLI', 8, NULL),
(180, 'Atlas Blue', 'Morocco', '8A', 'BMM', 6, NULL),
(197, 'Azerbaijan Airlines', 'Azerbaijan', 'J2', 'AHY', 24, NULL),
(198, 'Avies', 'Estonia', 'U3', 'AIA', 7, NULL),
(208, 'Airblue', 'Pakistan', 'ED', 'ABQ', 16, NULL),
(210, 'Airlift International', 'United States', NULL, 'AIR', 9, NULL),
(214, 'Air Berlin', 'Germany', 'AB', 'BER', 85, NULL),
(218, 'Air India Limited', 'India', 'AI', 'AIC', 135, NULL),
(220, 'Air Bourbon', 'Reunion', 'ZB', 'BUB', 4, NULL),
(221, 'Air Atlanta Icelandic', 'Iceland', 'CC', 'ABD', 18, NULL),
(225, 'Air Tahiti Nui', 'France', 'TN', 'THT', 5, NULL),
(231, 'Arkia Israel Airlines', 'Israel', 'IZ', 'AIZ', 12, NULL),
(239, 'Air Jamaica', 'Jamaica', 'JM', 'AJM', 11, NULL),
(240, 'Air One', 'Italy', 'AP', 'ADH', 28, NULL),
(241, 'Air Sahara', 'India', 'S2', 'RSH', 22, NULL),
(242, 'Air Malta', 'Malta', 'KM', 'AMC', 10, NULL),
(250, 'Air Japan', 'Japan', 'NQ', 'AJX', 8, NULL),
(252, 'Air Korea Co. Ltd.', 'Republic of Korea', NULL, 'AKA', 7, NULL),
(263, 'Air Kiribati', 'Kiribati', '4A', 'AKL', 2, NULL),
(281, 'America West Airlines', 'United States', 'HP', 'AWE', 142, NULL),
(282, 'Air Wisconsin', 'United States', 'ZW', 'AWI', 65, NULL),
(286, 'Tatarstan Airlines', 'Russia', 'U9', 'TAK', 18, NULL),
(287, 'Allegheny Commuter Airlines', 'United States', NULL, 'ALO', 45, NULL),
(295, 'Air Sunshine', 'United States', NULL, 'RSI', 8, NULL),
(299, 'Air Libert', 'France', 'VD', NULL, 12, NULL),
(306, 'Air Malawi', 'Malawi', 'QM', 'AML', 4, NULL),
(312, 'Air Sicilia', 'Italy', 'BM', NULL, 5, NULL),
(315, 'ATA Airlines', 'United States', NULL, 'AMT', 55, NULL),
(316, 'Air Macau', 'Macao', 'NX', 'AMU', 8, NULL),
(317, 'AMC Airlines', 'Egypt', NULL, 'AMV', 6, NULL),
(319, 'Air Seychelles', 'Seychelles', 'HM', 'SEY', 7, NULL),
(321, 'Aeromexico', 'Mexico', 'AM', 'AMX', 125, NULL),
(324, 'All Nippon Airways', 'Japan', 'NH', 'ANA', 245, 'ANA All Nippon Airways'),
(327, 'Air Nostrum', 'Spain', 'YW', 'ANE', 52, NULL),
(328, 'Air Niugini', 'Papua New Guinea', 'PX', 'ANG', 10, NULL),
(329, 'Air Arabia', 'United Arab Emirates', 'G9', 'ABY', 58, NULL),
(330, 'Air Canada', 'Canada', 'AC', 'ACA', 185, NULL),
(333, 'Air Baltic', 'Latvia', 'BT', 'BTI', 38, NULL),
(336, 'Air Nippon', 'Japan', 'EL', 'ANK', 22, NULL),
(338, 'Airnorth', 'Australia', 'TL', 'ANO', 9, NULL),
(341, 'Air North Charter - Canada', 'Canada', '4N', 'ANT', 7, NULL),
(345, 'Air New Zealand', 'New Zealand', 'NZ', 'ANZ', 105, NULL),
(371, 'Alitalia Express', 'Italy', 'XM', 'SMX', 25, NULL),
(386, 'Aero Flight', 'Germany', 'GV', 'ARF', 6, NULL),
(397, 'Arrow Air', 'United States', 'JW', 'APW', 8, NULL),
(410, 'Aerocondor', 'Portugal', '2B', 'ARD', 5, NULL),
(411, 'Aires', 'S.A.', '4C', 'ARE', 14, NULL),
(412, 'Aerolineas Argentinas', 'Argentina', 'AR', 'ARG', 75, NULL),
(439, 'Alaska Airlines', 'ALASKA', 'AS', 'ASA', 335, NULL),
(442, 'Air Sinai', 'Egypt', '4D', 'ASD', 3, NULL),
(452, 'Atlantic Southeast Airlines', 'United States', 'EV', 'ASQ', 165, NULL),
(462, 'Astrakhan Airlines', 'Russia', 'OB', 'ASZ', 5, NULL),
(465, 'Air Tanzania', 'Tanzania', 'TC', 'ATC', 8, NULL),
(470, 'Air Burkina', 'Burkina Faso', '2J', 'VBW', 4, NULL),
(476, 'Airlines Of Tasmania', 'Australia', 'FO', 'ATM', 6, NULL),
(477, 'Air Saint Pierre', 'France', 'PJ', 'SPM', 2, NULL),
(491, 'Austrian Airlines', 'Austria', 'OS', 'AUA', 82, NULL),
(492, 'Air Southwest', 'United Kingdom', NULL, 'WOW', 6, NULL),
(493, 'Augsburg Airways', 'Germany', 'IQ', 'AUB', 12, NULL),
(497, 'ATUR', 'Ecuador', NULL, 'TUR', 4, NULL),
(502, 'Abu Dhabi Amiri Flight', 'United Arab Emirates', 'MO', 'AUH', 15, NULL),
(503, 'Aeroflot-Nord', 'Russia', '5N', 'AUL', 16, NULL),
(508, 'Aurigny Air Services', 'United Kingdom', 'GR', 'AUR', 10, NULL),
(510, 'Austral Lineas Aereas', 'Argentina', 'AU', 'AUT', 18, NULL),
(515, 'Avianca - Aerovias Nacionales de Colombia', 'AVIANCA', 'AV', 'AVA', 165, NULL),
(524, 'Air Vanuatu', 'Vanuatu', 'NF', 'AVN', 5, NULL),
(543, 'Air Bangladesh', 'Bangladesh', 'B9', 'BGD', 7, NULL),
(547, 'Air Mediterranee', 'France', 'DR', 'BIE', 9, NULL),
(551, 'Air Moorea', 'France', NULL, 'TAH', 4, NULL),
(563, 'Aeroline GmbH', 'Germany', '7E', 'AWU', 5, NULL),
(565, 'Air Wales', 'United Kingdom', '6G', 'AWW', 4, NULL),
(567, 'Air Caraibes', 'France', 'TX', 'FWI', 9, NULL),
(569, 'Air India Express', 'India', 'IX', 'AXB', 25, NULL),
(575, 'Air Exel', 'Netherlands', 'XT', 'AXL', 12, NULL),
(576, 'AirAsia', 'Malaysia', 'AK', 'AXM', 245, 'Air Asia'),
(595, 'Atlant-Soyuz Airlines', 'Russia', '3G', 'AYZ', 11, NULL),
(596, 'Alitalia', 'Italy', 'AZ', 'AZA', 125, NULL),
(603, 'Amaszonas', 'Bolivia', 'Z8', 'AZN', 18, NULL),
(608, 'Air Zimbabwe', 'Zimbabwe', 'UM', 'AZW', 5, NULL),
(622, 'Aserca Airlines', 'Venezuela', 'R7', 'OCA', 9, NULL),
(641, 'Rossiya-Russian Airlines', 'Russia', 'FV', 'SDM', 55, 'Pulkovo Aviation Enterprise'),
(659, 'American Eagle Airlines', 'United States', 'MQ', 'EGF', 285, NULL),
(665, 'AD Aviation', 'United Kingdom', NULL, 'VUE', 4, NULL),
(682, 'Air Ivoire', 'Ivory Coast', 'VU', 'VUN', 5, NULL),
(683, 'Air Botswana', 'Botswana', 'BP', 'BOT', 6, NULL),
(690, 'Air Foyle', 'United Kingdom', 'GS', 'UPA', 8, NULL),
(692, 'Air Tahiti', 'French Polynesia', 'VT', 'VTA', 12, NULL),
(695, 'Air VIA', 'Bulgaria', 'VL', 'VIM', 7, NULL),
(715, 'Africa West', 'Togo', 'FK', 'WTA', 4, NULL),
(724, 'ATRAN Cargo Airlines', 'Russian Federation', 'V8', 'VAS', 10, NULL),
(751, 'Air China', 'China', 'CA', 'CCA', 685, NULL),
(753, 'Aero Condor Peru', 'Peru', 'Q6', 'CDP', 6, NULL),
(787, 'Air Chathams', 'New Zealand', 'CV', 'CVA', 8, NULL),
(788, 'Air Marshall Islands', 'Marshall Islands', 'CW', 'CWM', 3, NULL),
(792, 'Access Air', 'United States', 'ZA', 'CYD', 5, NULL),
(794, 'Air Algerie', 'Algeria', 'AH', 'DAH', 55, NULL),
(800, 'Adam Air', 'Indonesia', 'KI', 'DHI', 18, NULL),
(807, 'Air Dolomiti', 'Italy', 'EN', 'DLA', 28, NULL),
(816, 'Aeroflot-Don', 'Russia', 'D9', 'DNV', 14, NULL),
(817, 'Air Madrid', 'Spain', 'NM', 'DRD', 9, NULL),
(837, 'Aer Lingus', 'Ireland', 'EI', 'EIN', 55, NULL),
(876, 'Air Finland', 'Finland', 'OF', 'FIF', 7, NULL),
(878, 'Airfix Aviation', 'Finland', NULL, 'FIX', 4, NULL),
(879, 'Air Pacific', 'Fiji', 'FJ', 'FJI', 8, NULL),
(881, 'Atlantic Airways', 'Faroe Islands', 'RC', 'FLI', 6, NULL),
(882, 'Air Florida', 'United States', 'QH', 'FLZ', 32, NULL),
(896, 'Air Iceland', 'Iceland', 'NY', 'FXI', 14, NULL),
(897, 'Air Philippines', 'Philippines', '2P', 'GAP', 16, NULL),
(909, 'Air Guinee Express', 'Guinea', '2U', 'GIP', 4, NULL),
(921, 'Air Greenland', 'Denmark', 'GL', 'GRL', 9, NULL),
(928, 'Atlas Air', 'United States', '5Y', 'GTI', 52, NULL),
(931, 'Air Guyane', 'French Guiana', 'GG', 'GUY', 3, NULL),
(970, 'Air Bagan', 'Myanmar', 'W9', 'JAB', 7, NULL),
(983, 'Air Canada Jazz', 'Canada', 'QK', 'JZA', 125, NULL),
(995, 'Atlasjet', 'Turkey', 'KK', 'KKK', 22, NULL),
(998, 'Air Koryo', 'Democratic People''s Republic of Korea', 'JS', 'KOR', 18, NULL),
(1006, 'Air Astana', 'Kazakhstan', 'KC', 'KZR', 35, NULL),
(1008, 'Albanian Airlines', 'Albania', 'LV', 'LBC', 4, NULL),
(1017, 'Air Alfa', 'Turkey', NULL, 'LFA', 5, NULL),
(1034, 'Aerolane', 'Ecuador', 'XL', 'LNE', 6, NULL),
(1048, 'Atlantis European Airways', 'Armenia', 'TD', 'LUR', 5, NULL),
(1052, 'Air Luxor', 'Portugal', 'LK', 'LXR', 6, NULL),
(1057, 'Air Mauritius', 'Mauritius', 'MK', 'MAU', 12, NULL),
(1066, 'Air Madagascar', 'Madagascar', 'MD', 'MDG', 9, NULL),
(1073, 'Air Moldova', 'Moldova', '9U', 'MLD', 10, NULL),
(1087, 'Air Plus Comet', 'Spain', 'A7', 'MPD', 7, NULL),
(1109, 'Astair', 'Russian Federation', '8D', NULL, 4, NULL),
(1116, 'Aero Contractors', 'Nigeria', 'AJ', 'NIG', 15, NULL),
(1143, 'Aeropelican Air Services', 'Australia', 'OT', 'PEL', 8, NULL),
(1188, 'Aer Arann', 'Ireland', 'RE', 'REA', 16, NULL),
(1191, 'Air Austral', 'France', 'UU', 'REU', 11, NULL),
(1200, 'Asian Spirit', 'Philippines', '6K', 'RIT', 6, NULL),
(1202, 'Air Afrique', 'Ivory Coast', 'RK', 'RKA', 14, NULL),
(1203, 'Airlinair', 'France', 'A5', 'RLA', 22, NULL),
(1206, 'Aero Lanka', 'Sri Lanka', 'QL', 'RLN', 5, NULL),
(1213, 'Air Salone', 'Sierra Leone', '20', 'RNE', 3, NULL),
(1216, 'Armavia', 'Armenia', 'U8', 'RNV', 10, NULL),
(1224, 'AeroRep', 'Colombia', 'P5', 'RPB', 7, NULL),
(1230, 'Aero-Service', 'Republic of the Congo', 'BF', 'RSR', 4, NULL),
(1231, 'Aerosur', 'Bolivia', '5L', 'RSU', 12, NULL),
(1232, 'Aeronorte', 'Portugal', NULL, 'RTE', 5, NULL),
(1266, 'Avient Aviation', 'Zimbabwe', 'Z3', 'SMJ', 6, NULL),
(1287, 'Aircompany Yakutia', 'Russia', 'R3', 'SYL', 16, NULL),
(1290, 'Aeromar', 'Mexico', 'VW', 'TAO', 18, NULL),
(1299, 'Arkefly', 'Netherlands', 'OR', 'TFL', 12, NULL),
(1308, 'Airlines PNG', 'Papua New Guinea', 'CG', 'TOK', 10, NULL),
(1316, 'AirTran Airways', 'United States', 'FL', 'TRS', 138, NULL),
(1317, 'Air Transat', 'Canada', 'TS', 'TSC', 35, NULL),
(1322, 'Avialeasing Aviation Company', 'Uzbekistan', 'EC', 'TWN', 8, NULL),
(1326, 'Tyrolean Airways', 'Austria', 'VO', 'TYR', 28, NULL),
(1338, 'Aerolineas Galapagos (Aerogal)', 'Ecuador', '2K', 'GLG', 9, NULL),
(1340, 'Alrosa Mirny Air Enterprise', 'Russia', '6R', 'DRU', 12, NULL),
(1355, 'British Airways', 'United Kingdom', 'BA', 'BAW', 275, NULL),
(1359, 'Biman Bangladesh Airlines', 'Bangladesh', 'BG', 'BBC', 18, NULL),
(1401, 'Belair Airlines', 'Switzerland', '4T', 'BHP', 6, NULL),
(1403, 'Bahamasair', 'Bahamas', 'UP', 'BHS', 8, NULL),
(1411, 'British International Helicopters', 'United Kingdom', 'BS', 'BIH', 22, NULL),
(1420, 'BF-Lento OY', 'Finland', NULL, 'BKF', 4, NULL),
(1422, 'Bangkok Airways', 'Thailand', 'PG', 'BKP', 38, NULL),
(1427, 'Blue1', 'Finland', 'KF', 'BLF', 15, NULL),
(1431, 'Baltic Airlines', 'Russia', NULL, 'BLL', 6, NULL),
(1434, 'Bearskin Lake Air Service', 'Canada', 'JV', 'BLS', 18, NULL),
(1436, 'Bellview Airlines', 'Nigeria', 'B3', 'BLV', 12, NULL),
(1437, 'bmi', 'United Kingdom', 'BD', 'BMA', 48, 'bmi British Midland'),
(1441, 'bmibaby', 'United Kingdom', 'WW', 'BMI', 22, NULL),
(1442, 'Bemidji Airlines', 'United States', 'CH', 'BMJ', 9, NULL),
(1445, 'British Midland Regional', 'United Kingdom', NULL, 'BMR', 25, NULL),
(1463, 'Blue Panorama Airlines', 'Italy', 'BV', 'BPA', 11, NULL),
(1466, 'Budapest Aircraft Services/Manx2', 'Hungary', NULL, 'BPS', 5, NULL),
(1472, 'Bering Air', 'United States', '8E', 'BRG', 12, NULL),
(1476, 'Brazilian Air Force', 'Brazil', NULL, 'BRS', 125, NULL),
(1478, 'Belavia Belarusian Airlines', 'Belarus', 'B2', 'BRU', 28, NULL),
(1500, 'Metro Batavia', 'Indonesia', '7P', 'BTV', 14, NULL),
(1508, 'Berjaya Air', 'Malaysia', 'J8', 'BVT', 6, NULL),
(1510, 'Blue Wings', 'Germany', 'QW', 'BWG', 5, NULL),
(1523, 'Brit Air', 'France', 'DB', 'BZH', 28, NULL),
(1531, 'Brussels Airlines', 'Belgium', 'SN', 'DAT', 52, 'SN Brussels Airlines'),
(1539, 'Binter Canarias', 'Spain', 'NT', 'IBB', 22, NULL),
(1542, 'Blue Air', 'Romania', '0B', 'JOR', 28, NULL),
(1543, 'British Mediterranean Airways', 'United Kingdom', 'KJ', 'LAJ', 8, NULL),
(1548, 'Bulgaria Air', 'Bulgaria', 'FB', 'LZB', 18, NULL),
(1550, 'Barents AirLink', 'Sweden', '8N', 'NKF', 5, NULL),
(1581, 'CAL Cargo Air Lines', 'Israel', '5C', 'ICL', 10, NULL),
(1607, 'Calima Aviacion', 'Spain', 'XG', 'CLI', 4, NULL),
(1615, 'Canadian Airlines', 'Canada', 'CP', 'CDN', 95, NULL),
(1623, 'Canadian North', 'Canada', '5T', 'MPE', 24, NULL),
(1629, 'Cape Air', 'United States', '9K', 'KAP', 85, NULL),
(1663, 'Caribbean Airlines', 'Trinidad and Tobago', 'BW', 'BWA', 16, NULL),
(1669, 'Carpatair', 'Romania', 'V3', 'KRP', 14, NULL),
(1675, 'Caspian Airlines', 'Iran', 'RV', 'CPN', 8, NULL),
(1680, 'Cathay Pacific', 'Hong Kong SAR of China', 'CX', 'CPA', 195, NULL),
(1682, 'Cayman Airways', 'Cayman Islands', 'KX', 'CAY', 5, NULL),
(1683, 'Cebu Pacific', 'Philippines', '5J', 'CEB', 78, NULL),
(1700, 'Central Connect Airlines', 'Czech Republic', NULL, 'CCG', 4, NULL),
(1708, 'Centralwings', 'Poland', 'C0', 'CLW', 8, NULL),
(1737, 'Charter Air', 'Austria', NULL, 'CHW', 5, NULL),
(1739, 'Chautauqua Airlines', 'United States', 'RP', 'CHQ', 85, NULL),
(1756, 'China Airlines', 'Taiwan', 'CI', 'CAL', 92, NULL),
(1758, 'China Eastern Airlines', 'China', 'MU', 'CES', 725, NULL),
(1767, 'China Southern Airlines', 'China', 'CZ', 'CSN', 865, NULL),
(1769, 'China United Airlines', 'China', 'HR', 'CUA', 48, NULL),
(1771, 'Yunnan Airlines', 'China', '3Q', 'CYH', 22, NULL),
(1781, 'Cimber Air', 'Denmark', 'QI', 'CIM', 18, NULL),
(1784, 'Cirrus Airlines', 'Germany', 'C9', 'RUS', 12, NULL),
(1789, 'City Airline', 'Sweden', 'CF', 'SDR', 9, NULL),
(1790, 'City Connexion Airlines', 'Burundi', 'G3', 'CIX', 4, NULL),
(1792, 'CityJet', 'Ireland', 'WX', 'BCY', 28, NULL),
(1795, 'BA CityFlyer', 'United Kingdom', 'CJ', 'CFE', 45, NULL),
(1808, 'Click Airways', 'Kyrgyzstan', NULL, 'CGK', 3, NULL),
(1814, 'Coastal Air', 'United States', 'DQ', NULL, 8, NULL),
(1821, 'Colgan Air', 'United States', '9L', 'CJC', 55, NULL),
(1828, 'Comair', 'United States', 'OH', 'COM', 135, NULL),
(1829, 'Comair', 'South Africa', 'MN', 'CAW', 28, NULL),
(1843, 'CommutAir', 'United States', 'C5', 'UCA', 48, NULL),
(1844, 'Comores Airlines', 'Comoros', 'KR', 'CWK', 3, NULL),
(1860, 'Compass Airlines', 'United States', 'CP', 'CPZ', 42, NULL),
(1868, 'Condor Flugdienst', 'Germany', 'DE', 'CFG', 55, NULL),
(1876, 'Consorcio Aviaxsa', 'Mexico', '6A', 'CHP', 11, NULL),
(1879, 'Contact Air', 'Germany', 'C3', 'KIS', 18, 'Contactair'),
(1881, 'Continental Airlines', 'United States', 'CO', 'COA', 365, NULL),
(1883, 'Continental Express', 'United States', 'CO', NULL, 245, NULL),
(1884, 'Continental Micronesia', 'United States', 'CS', 'CMI', 18, NULL),
(1886, 'Conviasa', 'Venezuela', 'V0', 'VCV', 22, NULL),
(1889, 'Copa Airlines', 'Panama', 'CM', 'CMP', 102, NULL),
(1892, 'Copterline', 'Finland', NULL, 'AAQ', 8, NULL),
(1894, 'Corendon Airlines', 'Turkey', NULL, 'CAI', 15, NULL),
(1908, 'Corsairfly', 'France', 'SS', 'CRL', 8, NULL),
(1909, 'Corse-Mediterranee', 'France', 'XK', 'CCM', 6, NULL),
(1923, 'Crest Aviation', 'United Kingdom', NULL, 'CAN', 4, NULL),
(1925, 'Croatia Airlines', 'Croatia', 'OU', 'CTN', 12, NULL),
(1931, 'Crown Airways', 'United States', NULL, 'CRO', 5, NULL),
(1936, 'Cubana de Aviacion', 'Cuba', 'CU', 'CUB', 18, NULL),
(1942, 'Cyprus Airways', 'Cyprus', 'CY', 'CYP', 11, NULL),
(1943, 'Cyprus Turkish Airlines', 'Turkey', 'YK', NULL, 6, NULL),
(1946, 'Czech Airlines', 'Czech Republic', 'OK', 'CSA', 42, 'CSA Czech Airlines'),
(1954, 'DAT Danish Air Transport', 'Denmark', 'DX', 'DTR', 16, NULL),
(1966, 'Daallo Airlines', 'Djibouti', 'D3', 'DAO', 6, NULL),
(1973, 'Dalavia', 'Russia', 'H8', 'KHB', 12, NULL),
(1983, 'Darwin Airline', 'Switzerland', '0D', 'DWT', 8, NULL),
(2006, 'Delta Aerotaxi', 'Italy', NULL, 'DEA', 4, NULL),
(2009, 'Delta Air Lines', 'United States', 'DL', 'DAL', 925, NULL),
(2013, 'Denim Air', 'Netherlands', NULL, 'DNM', 5, NULL),
(2021, 'Deutsche Bahn', 'Germany', '2A', NULL, 0, NULL),
(2041, 'Djibouti Airlines', 'Djibouti', 'D8', 'DJB', 4, NULL),
(2042, 'Dniproavia', 'Ukraine', NULL, 'UDN', 8, NULL),
(2047, 'Dominicana de Aviaci', 'Dominican Republic', 'DO', 'DOA', 6, NULL),
(2048, 'Domodedovo Airlines', 'Russia', 'E3', 'DMO', 14, NULL),
(2051, 'DonbassAero', 'Ukraine', '5D', 'UDC', 11, NULL),
(2056, 'Dragonair', 'DRAGON', 'KA', 'HDA', 38, NULL),
(2058, 'Druk Air', 'Bhutan', 'KB', 'DRK', 5, NULL),
(2061, 'Dubrovnik Air', 'Croatia', NULL, 'DBK', 3, NULL),
(2070, 'Dutch Antilles Express', 'Netherlands Antilles', NULL, 'DNL', 6, NULL),
(2077, 'dba', 'Germany', 'DI', 'BAG', 28, NULL),
(2091, 'EVA Air', 'Taiwan', 'BR', 'EVA', 82, NULL),
(2094, 'Eagle Air', 'Uganda', 'H7', NULL, 5, NULL),
(2104, 'East African', 'Uganda', 'QU', 'UGX', 6, NULL),
(2117, 'Eastern Airways', 'United Kingdom', 'T3', 'EZE', 42, NULL),
(2125, 'Eastland Air', 'Australia', 'DK', 'ELA', 7, NULL),
(2137, 'Ecuavia', 'Ecuador', NULL, 'ECU', 5, NULL),
(2138, 'Edelweiss Air', 'Switzerland', 'WK', 'EDW', 18, NULL),
(2143, 'Egyptair', 'Egypt', 'MS', 'MSR', 68, NULL),
(2150, 'El Al Israel Airlines', 'Israel', 'LY', 'ELY', 45, NULL),
(2155, 'El-Buraq Air Transport', 'Libya', 'UZ', 'BRQ', 6, NULL),
(2183, 'Emirates', 'United Arab Emirates', 'EK', 'UAE', 275, 'Emirates Airlines'),
(2193, 'Empresa Ecuatoriana De Aviacion', 'Ecuador', 'EU', 'EEA', 8, NULL),
(2213, 'Eritrean Airlines', 'Eritrea', 'B8', 'ERT', 4, NULL),
(2218, 'Estonian Air', 'Estonia', 'OV', 'ELL', 9, NULL),
(2220, 'Ethiopian Airlines', 'Ethiopia', 'ET', 'ETH', 125, NULL),
(2222, 'Etihad Airways', 'United Arab Emirates', 'EY', 'ETD', 115, NULL),
(2226, 'Euro Exec Express', 'Sweden', 'RZ', NULL, 4, NULL),
(2237, 'Eurocypria Airlines', 'Cyprus', 'UI', 'ECA', 5, NULL),
(2239, 'Eurofly Service', 'Italy', 'GJ', 'EEU', 9, NULL),
(2245, 'Eurolot', 'Poland', 'K2', 'ELO', 16, NULL),
(2251, 'European Air Express', 'Germany', 'EA', 'EAL', 11, NULL),
(2260, 'Eurowings', 'Germany', 'EW', 'EWG', 95, NULL),
(2261, 'Evergreen International Airlines', 'United States', 'EZ', 'EIA', 18, NULL),
(2264, 'Excel Airways', 'United Kingdom', 'JN', 'XLA', 6, NULL),
(2265, 'Excel Charter', 'United Kingdom', NULL, 'XEL', 5, NULL),
(2293, 'Express One International', 'United States', 'EO', 'LHN', 8, NULL),
(2295, 'ExpressJet', 'United States', 'XE', 'BTA', 165, NULL),
(2297, 'easyJet', 'United Kingdom', 'U2', 'EZY', 335, 'EasyJet Airline'),
(2324, 'Far Eastern Air Transport', 'Taiwan', 'EF', 'EFA', 16, NULL),
(2350, 'Finnair', 'Finland', 'AY', 'FIN', 78, NULL),
(2351, 'Finncomm Airlines', 'Finland', 'FC', 'WBA', 12, NULL),
(2353, 'Firefly', 'Malaysia', 'FY', 'FFM', 18, NULL),
(2354, 'First Air', 'Canada', '7F', 'FAB', 25, NULL),
(2357, 'First Choice Airways', 'United Kingdom', 'DP', 'FCA', 35, NULL),
(2395, 'Flightline', 'United Kingdom', 'B5', 'FLT', 6, NULL),
(2404, 'Florida West International Airways', 'United States', 'RF', 'FWL', 8, NULL),
(2417, 'AirAsia X', 'Malaysia', 'D7', 'XAX', 32, 'FlyAsianXpress'),
(2418, 'FlyLal', 'Lithuania', 'TE', 'LIL', 9, NULL),
(2419, 'FlyNordic', 'Sweden', 'LF', 'NDC', 7, NULL),
(2420, 'Flybaboo', 'Switzerland', 'F7', 'BBO', 6, NULL),
(2421, 'Flybe', 'United Kingdom', 'BE', 'BEE', 68, NULL),
(2425, 'Flyglobespan', 'United Kingdom', 'B4', 'GSM', 12, NULL),
(2429, 'Flyhy Cargo Airlines', 'Thailand', NULL, 'FYH', 5, NULL),
(2439, 'Formosa Airlines', 'Taiwan', 'VY', 'FOS', 8, NULL),
(2454, 'Freedom Air', 'United States', 'FP', 'FRE', 6, NULL),
(2456, 'Freedom Airlines', 'United States', NULL, 'FRL', 9, NULL),
(2468, 'Frontier Airlines', 'United States', 'F9', 'FFT', 115, NULL),
(2470, 'Frontier Flying Service', 'United States', '2F', 'FTA', 12, NULL),
(2486, 'GB Airways', 'United Kingdom', 'GT', 'GBL', 18, NULL),
(2520, 'Garuda Indonesia', 'Indonesia', 'GA', 'GIA', 145, NULL),
(2524, 'Gazpromavia', 'Russia', '4G', 'GZP', 28, NULL),
(2538, 'Georgian Airways', 'Georgia', 'A9', 'TGZ', 8, NULL),
(2541, 'Georgian National Airlines', 'Georgia', 'QB', 'GFG', 6, NULL),
(2547, 'Germania', 'Germany', 'ST', 'GMI', 28, NULL),
(2548, 'Germanwings', 'Germany', '4U', 'GWI', 55, NULL),
(2556, 'Ghana International Airlines', 'Ghana', 'G0', 'GHB', 5, NULL),
(2575, 'Go Air', 'India', 'G8', 'GOW', 58, NULL),
(2577, 'GoJet Airlines', 'United States', 'G7', 'GJS', 38, NULL),
(2581, 'Gol Transportes Aereos', 'Brazil', 'G3', 'GLO', 125, NULL),
(2585, 'Golden Air', 'Sweden', 'DC', 'GAO', 8, NULL),
(2607, 'Great Lakes Airlines', 'United States', 'ZK', 'GLA', 28, NULL),
(2622, 'Grupo TACA', 'Costa Rica', 'TA', 'TAT', 95, 'TACA'),
(2637, 'Gulf Air', 'Oman', NULL, 'GFA', 32, NULL),
(2638, 'Gulf Air Bahrain', 'Bahrain', 'GF', 'GBA', 28, NULL),
(2645, 'Gulfstream International Airlines', 'United States', NULL, 'GFT', 18, NULL),
(2657, 'Hageland Aviation Services', 'United States', 'H6', 'HAG', 15, NULL),
(2660, 'Hainan Airlines', 'China', 'HU', 'CHH', 235, NULL),
(2663, 'Haiti Ambassador Airlines', 'Haiti', '2T', 'HAM', 4, NULL),
(2674, 'Hamburg International', 'Germany', '4R', 'HHI', 8, NULL),
(2681, 'TUIfly', 'Germany', 'X3', 'HLX', 42, NULL),
(2682, 'Hapagfly', 'Germany', 'HF', 'HLF', 7, NULL),
(2688, 'Hawaiian Airlines', 'United States', 'HA', 'HAL', 62, NULL),
(2692, 'Hawkair', 'Canada', 'BH', NULL, 6, NULL),
(2704, 'Heli France', 'France', '8H', 'HFR', 12, NULL),
(2731, 'Helijet', 'Canada', 'JB', 'JBA', 15, NULL),
(2747, 'Hellas Jet', 'Greece', 'T4', 'HEJ', 5, NULL),
(2748, 'Hello', 'Switzerland', 'HW', 'FHE', 4, NULL),
(2750, 'Helvetic Airways', 'Switzerland', '2L', 'OAW', 12, NULL),
(2757, 'Hex Air', 'France', 'UD', 'HER', 5, NULL),
(2761, 'Highland Airways', 'United Kingdom', NULL, 'HWY', 6, NULL),
(2765, 'Hokkaido International Airlines', 'Japan', 'HD', 'ADO', 15, NULL),
(2773, 'Hong Kong Airlines', 'Hong Kong SAR of China', 'HX', 'CRK', 38, NULL),
(2774, 'Hong Kong Express Airways', 'Hong Kong SAR of China', 'UO', 'HKE', 28, NULL),
(2778, 'Horizon Air', 'United States', 'QX', 'QXE', 78, 'Horizon Airlines'),
(2782, 'Horizon Airlines', 'Australia', 'BN', 'HZA', 5, NULL),
(2822, 'Iberia Airlines', 'Spain', 'IB', 'IBE', 135, NULL),
(2825, 'Iberworld', 'Spain', 'TY', 'IWD', 9, NULL),
(2826, 'Ibex Airlines', 'Japan', 'FW', 'IBX', 18, NULL),
(2829, 'Icar Air', 'Bosnia and Herzegovina', NULL, 'RAC', 4, NULL),
(2835, 'Icelandair', 'Iceland', 'FI', 'ICE', 38, NULL),
(2845, 'Imair Airlines', 'Azerbaijan', 'IK', 'ITX', 5, NULL),
(2850, 'IndiGo Airlines', 'India', '6E', 'IGO', 285, NULL),
(2853, 'Indian Airlines', 'India', 'IC', 'IAC', 62, NULL),
(2855, 'Indigo', 'United States', 'I9', 'IBU', 6, NULL),
(2857, 'Indonesia AirAsia', 'Indonesia', 'QZ', 'AWQ', 48, NULL),
(2858, 'Indonesian Airlines', 'Indonesia', 'IO', 'IAA', 22, NULL),
(2881, 'Interair South Africa', 'South Africa', 'D6', 'ILN', 12, NULL),
(2883, 'Interavia Airlines', 'Russia', 'ZA', 'SUW', 9, NULL),
(2896, 'Interlink Airlines', 'South Africa', 'ID', 'ITK', 8, NULL),
(2916, 'Intersky', 'Austria', '3L', 'ISK', 11, NULL),
(2922, 'Iran Air', 'Iran', 'IR', 'IRA', 42, NULL),
(2923, 'Iran Aseman Airlines', 'Iran', 'EP', 'IRC', 28, NULL),
(2926, 'Iraqi Airways', 'Iraq', 'IA', 'IAW', 16, NULL),
(2937, 'Island Airlines', 'United States', 'IS', NULL, 7, NULL),
(2942, 'Cargo Plus Aviation', 'United Arab Emirates', '8L', 'CGP', 12, NULL),
(2948, 'Islas Airways', 'Spain', 'IF', 'ISW', 6, NULL),
(2950, 'Islena De Inversiones', 'Honduras', 'WC', 'ISV', 5, NULL),
(2954, 'Israir', 'Israel', '6H', 'ISR', 12, NULL),
(2958, 'Itek Air', 'Kyrgyzstan', 'GI', 'IKA', 6, NULL),
(2969, 'JAL Express', 'Japan', 'JC', 'JEX', 22, NULL),
(2970, 'JALways', 'Japan', 'JO', 'JAZ', 15, NULL),
(2987, 'Japan Airlines', 'Japan', 'JL', 'JAL', 165, 'JAL Japan Airlines'),
(2988, 'Japan Airlines Domestic', 'Japan', 'JL', 'JAL', 95, NULL),
(2989, 'Japan Asia Airways', 'Japan', 'EG', 'JAA', 12, NULL),
(2990, 'Japan Transocean Air', 'Japan', 'NU', 'JTA', 18, NULL),
(2993, 'Jazeera Airways', 'Kuwait', 'J9', 'JZR', 12, NULL),
(2994, 'Jeju Air', 'Republic of Korea', '7C', 'JJA', 42, NULL),
(3000, 'Jet Airways', 'India', '9W', 'JAI', 115, NULL),
(3001, 'Jet Airways', 'United States', 'QJ', NULL, 8, NULL),
(3021, 'Jetstar Asia Airways', 'Singapore', '3K', 'JSA', 18, NULL),
(3026, 'Jet2.com', 'United Kingdom', 'LS', 'EXS', 95, NULL),
(3027, 'Jet4You', 'Morocco', '8J', 'JFU', 9, NULL),
(3029, 'JetBlue Airways', 'United States', 'B6', 'JBU', 285, NULL),
(3032, 'Jetairfly', 'Belgium', 'JF', 'JAF', 18, NULL),
(3039, 'Jetflite', 'Finland', NULL, 'JEF', 5, NULL),
(3052, 'Jetstar Airways', 'Australia', 'JQ', 'JST', 85, NULL),
(3081, 'Juneyao Airlines', 'China', 'HO', 'DKH', 78, NULL),
(3087, 'KD Avia', 'Russia', 'KD', 'KNI', 14, NULL),
(3088, 'KLM Cityhopper', 'Netherlands', 'WA', 'KLC', 48, NULL),
(3090, 'KLM Royal Dutch Airlines', 'Netherlands', 'KL', 'KLM', 115, NULL),
(3097, 'Kam Air', 'Afghanistan', 'RQ', 'KMF', 8, NULL),
(3110, 'Kavminvodyavia', 'Russia', 'KV', 'MVD', 12, NULL),
(3122, 'Kendell Airlines', 'Australia', NULL, 'KDA', 18, NULL),
(3123, 'Kenmore Air', 'United States', 'M5', 'KEN', 15, NULL),
(3126, 'Kenya Airways', 'Kenya', 'KQ', 'KQA', 38, NULL),
(3142, 'Kingfisher Airlines', 'India', 'IT', 'KFR', 65, NULL),
(3148, 'Kish Air', 'Iran', 'Y9', 'IRK', 12, NULL),
(3157, 'Kogalymavia Air Company', 'Russia', '7K', 'KGL', 18, NULL),
(3163, 'Korean Air', 'Republic of Korea', 'KE', 'KAL', 165, NULL),
(3165, 'Kosmos', 'Russia', NULL, 'KSM', 8, NULL),
(3168, 'Krasnojarsky Airlines', 'Russia', '7B', 'KJC', 11, NULL),
(3175, 'Kuban Airlines', 'Russia', 'GW', 'KIL', 9, NULL),
(3179, 'Kuwait Airways', 'Kuwait', 'KU', 'KAC', 32, NULL),
(3180, 'Kuzu Airlines Cargo', 'Turkey', 'GO', 'KZU', 8, NULL),
(3197, 'LACSA', 'Costa Rica', 'LR', 'LRC', 18, NULL),
(3200, 'LAN Airlines', 'Chile', 'LA', 'LAN', 145, NULL),
(3201, 'LAN Argentina', 'Argentina', '4M', 'DSM', 22, NULL),
(3204, 'LAN Express', 'Chile', 'LU', 'LXP', 18, NULL),
(3205, 'LAN Peru', 'Peru', 'LP', 'LPE', 22, NULL),
(3210, 'LOT Polish Airlines', 'Poland', 'LO', 'LOT', 78, NULL),
(3211, 'LTE International Airways', 'Spain', 'XO', 'LTE', 9, NULL),
(3212, 'LTU Austria', 'Austria', 'L3', 'LTO', 6, NULL),
(3233, 'Lao Airlines', 'Lao Peoples Democratic Republic', 'QV', 'LAO', 14, NULL),
(3237, 'LatCharter', 'Latvia', NULL, 'LTC', 5, NULL),
(3239, 'Lauda Air', 'Austria', 'NG', 'LDA', 22, NULL),
(3251, 'Leeward Islands Air Transport', 'Antigua and Barbuda', 'LI', 'LIA', 8, NULL),
(3258, 'Libyan Arab Airlines', 'Libya', 'LN', 'LAA', 18, NULL),
(3287, 'Linhas A', 'Mozambique', 'LM', 'LAM', 9, NULL),
(3290, 'Lion Mentari Airlines', 'Indonesia', 'JT', 'LNI', 115, NULL),
(3319, 'Luftfahrtgesellschaft Walter', 'Germany', 'HE', 'LGW', 38, NULL),
(3320, 'Lufthansa', 'Germany', 'LH', 'DLH', 285, NULL),
(3321, 'Lufthansa Cargo', 'Germany', 'LH', 'GEC', 18, NULL),
(3322, 'Lufthansa CityLine', 'Germany', 'CL', 'CLH', 68, NULL),
(3326, 'Lufttransport', 'Norway', 'L5', 'LTR', 6, NULL),
(3329, 'Luxair', 'Luxembourg', 'LG', 'LGL', 18, NULL),
(3342, 'L', 'Argentina', 'MJ', 'LPR', 12, NULL),
(3349, 'MasAir', 'Mexico', 'M7', 'MAA', 9, NULL),
(3350, 'MAT Macedonian Airlines', 'Macedonia', 'IN', 'MAK', 6, NULL),
(3354, 'MIAT Mongolian Airlines', 'Mongolia', 'OM', 'MGL', 12, NULL),
(3357, 'MNG Airlines', 'Turkey', 'MB', 'MNB', 22, NULL),
(3363, 'Macair Airlines', 'Australia', 'CC', 'MCK', 5, NULL),
(3366, 'Maersk', 'Denmark', 'DM', NULL, 28, NULL),
(3370, 'Mahan Air', 'Iran', 'W5', 'IRM', 58, NULL),
(3378, 'Malaysia Airlines', 'Malaysia', 'MH', 'MAS', 82, NULL),
(3384, 'Malmo Aviation', 'Sweden', NULL, 'SCW', 9, NULL),
(3386, 'Malmo Aviation', 'Sweden', 'TF', 'SCW', 8, NULL),
(3387, 'Malta Air Charter', 'Malta', 'R5', 'MAC', 5, NULL),
(3389, 'Malev', 'Hungary', 'MA', 'MAH', 18, NULL),
(3391, 'Mandala Airlines', 'Indonesia', 'RI', 'MDL', 15, NULL),
(3392, 'Mandarin Airlines', 'Taiwan', 'AE', 'MDA', 12, NULL),
(3393, 'Mango', 'South Africa', 'JE', 'MNO', 12, NULL),
(3411, 'Martinair', 'Netherlands', 'MP', 'MPH', 15, NULL),
(3432, 'Maxair', 'Sweden', '8M', 'MXL', 6, NULL),
(3437, 'Maya Island Air', 'Belize', 'MW', 'MYD', 8, NULL),
(3463, 'Meridiana', 'Italy', 'IG', 'ISS', 22, NULL),
(3465, 'Merpati Nusantara Airlines', 'Indonesia', 'MZ', 'MNA', 28, NULL),
(3466, 'Mesa Airlines', 'United States', 'YV', 'ASH', 145, NULL),
(3467, 'Mesaba Airlines', 'United States', 'XJ', 'MES', 95, NULL),
(3479, 'Mexicana de Aviaci', 'Mexico', 'MX', 'MXA', 55, NULL),
(3490, 'Middle East Airlines', 'Lebanon', 'ME', 'MEA', 22, NULL),
(3494, 'Midway Airlines', 'United States', 'JI', 'MDW', 18, NULL),
(3497, 'Midwest Airlines', 'United States', 'YX', 'MEP', 22, NULL),
(3498, 'Midwest Airlines (Egypt)', 'Egypt', 'MY', 'MWA', 8, NULL),
(3529, 'Moldavian Airlines', 'Moldova', '2M', 'MDV', 9, NULL),
(3532, 'Monarch Airlines', 'United Kingdom', 'ZB', 'MON', 42, NULL),
(3534, 'Myway Airlines', 'Italy', '8I', NULL, 5, NULL),
(3539, 'Montenegro Airlines', 'Montenegro', 'YM', 'MGX', 6, NULL),
(3542, 'Morningstar Air Express', 'Canada', NULL, 'MAL', 8, NULL),
(3545, 'Moskovia Airlines', 'Russia', '3R', 'GAI', 18, NULL),
(3547, 'Motor Sich', 'Ukraine', 'M9', 'MSI', 12, NULL),
(3568, 'MyTravel Airways', 'United Kingdom', 'VZ', 'MYT', 28, NULL),
(3569, 'Myanma Airways', 'Myanmar', 'UB', 'UBA', 12, NULL),
(3570, 'Myanmar Airways International', 'Myanmar', '8M', 'MMM', 8, NULL),
(3571, 'Myflug', 'Iceland', NULL, 'MYA', 4, NULL),
(3589, 'Nasair', 'Eritrea', 'UE', 'NAS', 4, NULL),
(3608, 'National Jet Systems', 'Australia', 'NC', 'NJS', 32, NULL),
(3613, 'Nationwide Airlines', 'South Africa', 'CE', 'NTW', 9, NULL),
(3618, 'Nauru Air Corporation', 'Nauru', 'ON', 'RON', 2, NULL),
(3637, 'Nepal Airlines', 'Nepal', 'RA', 'RNA', 9, NULL),
(3641, 'NetJets', 'United States', '1I', 'EJA', 685, NULL),
(3644, 'New England Airlines', 'United States', 'EJ', 'NEA', 12, NULL),
(3652, 'NextJet', 'Sweden', '2N', 'NTJ', 9, NULL),
(3661, 'Niki', 'Austria', 'HG', 'NLY', 22, NULL),
(3674, 'Nok Air', 'Thailand', 'DD', 'NOK', 28, NULL),
(3684, 'Norfolk County Flight College', 'United Kingdom', NULL, 'NCF', 8, NULL),
(3693, 'North American Airlines', 'Canada', NULL, 'NTM', 6, NULL),
(3694, 'North American Charters', 'Canada', NULL, 'HMR', 5, NULL),
(3721, 'Northern Dene Airways', 'Canada', 'U7', NULL, 8, NULL),
(3731, 'Northwest Airlines', 'United States', 'NW', 'NWA', 375, NULL),
(3734, 'Northwestern Air', 'Canada', 'J3', 'PLR', 12, NULL),
(3737, 'Norwegian Air Shuttle', 'Norway', 'DY', 'NAX', 165, NULL),
(3738, 'Norwegian Aviation College', 'Norway', NULL, 'TFN', 6, NULL),
(3740, 'Nouvel Air Tunisie', 'Tunisia', 'BJ', 'LBT', 8, NULL),
(3743, 'Novair', 'Sweden', '1I', 'NVR', 7, NULL),
(3754, 'Nas Air', 'Saudi Arabia', 'XY', 'KNE', 32, NULL),
(3759, 'Oasis Hong Kong Airlines', 'Hong Kong', 'O8', 'OHK', 8, NULL),
(3760, 'Ocean Air', 'Mauritania', NULL, 'BCN', 3, NULL),
(3764, 'Oceanair', 'Brazil', 'O6', 'ONE', 28, NULL),
(3765, 'Oceanic Airlines', 'Guinea', 'O2', NULL, 4, NULL),
(3776, 'Olympic Airlines', 'Greece', 'OA', 'OAL', 38, NULL),
(3778, 'Oman Air', 'Oman', 'WY', 'OMA', 52, NULL),
(3781, 'Omni Air International', 'United States', 'OY', 'OAE', 12, NULL),
(3785, 'One Two Go Airlines', 'Thailand', NULL, 'OTG', 9, NULL),
(3788, 'Onur Air', 'Turkey', '8Q', 'OHY', 28, NULL),
(3805, 'Orenburg Airlines', 'Russia', 'R2', 'ORB', 18, NULL),
(3811, 'Orient Thai Airlines', 'Thailand', 'OX', 'OEA', 22, NULL),
(3814, 'Origin Pacific Airways', 'New Zealand', 'QO', 'OGN', 6, NULL),
(3822, 'Ostfriesische Lufttransport', 'Germany', 'OL', 'OLT', 12, NULL),
(3826, 'Overland Airways', 'Nigeria', 'OJ', 'OLA', 8, NULL),
(3831, 'Ozjet Airlines', 'Australia', 'O7', 'OZJ', 5, NULL),
(3834, 'PAN Air', 'Spain', 'PV', 'PNR', 6, NULL),
(3835, 'PB Air', 'Thailand', '9Q', 'PBA', 7, NULL),
(3839, 'PLUNA', 'Uruguay', 'PU', 'PUA', 9, NULL),
(3840, 'PMTair', 'Cambodia', 'U4', 'PMT', 4, NULL),
(3850, 'Jetstar Pacific', 'Vietnam', 'BL', 'PIC', 18, 'Pacific Airlines'),
(3856, 'Pacific Coastal Airline', 'Canada', '8P', 'PCO', 15, NULL),
(3857, 'Pacific East Asia Cargo Airlines', 'Philippines', 'Q8', 'PEC', 8, NULL),
(3860, 'Pacific Island Aviation', 'United States', NULL, 'PSA', 6, NULL),
(3865, 'Pacific Wings', 'United States', 'LW', 'NMI', 9, NULL),
(3871, 'Pakistan International Airlines', 'Pakistan', 'PK', 'PIA', 42, 'PIA Pakistan International'),
(3907, 'Paramount Airways', 'India', 'I7', 'PMW', 8, NULL),
(3914, 'Passaredo Transportes Aereos', 'Brazil', NULL, 'PTB', 28, NULL),
(3926, 'Pegasus Airlines', 'Turkey', 'PC', 'PGT', 92, NULL),
(3935, 'Peninsula Airways', 'United States', 'KS', 'PEN', 18, NULL),
(3952, 'Philippine Airlines', 'Philippines', 'PR', 'PAL', 75, NULL),
(3969, 'Piedmont Airlines (1948-1989)', 'United States', 'PI', 'PDT', 185, NULL),
(3976, 'Pinnacle Airlines', 'United States', '9E', 'FLG', 165, NULL),
(3995, 'Polet', 'Russia', NULL, 'POT', 12, NULL),
(4013, 'Polynesian Airlines', 'Samoa', 'PH', 'PAO', 5, NULL),
(4021, 'Porter Airlines', 'Canada', 'PD', 'POE', 28, NULL),
(4022, 'Portugalia', 'Portugal', 'NI', 'PGA', 18, NULL),
(4026, 'Potomac Air', 'United States', 'BK', 'PDC', 8, NULL),
(4031, 'Precision Air', 'Tanzania', 'PW', 'PRF', 12, NULL),
(4056, 'Privatair', 'Switzerland', NULL, 'PTI', 8, NULL),
(4066, 'Proflight Commuter Services', 'Zambia', 'P0', NULL, 6, NULL),
(4089, 'Qantas', 'Australia', 'QF', 'QFA', 135, 'Qantas Airways'),
(4091, 'Qatar Airways', 'Qatar', 'QR', 'QTR', 245, NULL),
(4106, 'RACSA', 'Guatemala', 'R6', NULL, 4, NULL),
(4113, 'Kinloss Flying Training Unit', 'United Kingdom', NULL, 'KIN', 12, NULL),
(4177, 'Regional Airlines', 'Morocco', 'FN', NULL, 8, NULL),
(4178, 'Regional Express', 'Australia', 'ZL', 'RXA', 58, NULL),
(4187, 'Republic Airlines', 'United States', 'RW', 'RPA', 225, NULL),
(4188, 'Republic Express Airlines', 'Indonesia', 'RH', 'RPH', 9, NULL),
(4232, 'Rossiya', 'Russia', 'R4', NULL, 62, NULL),
(4234, 'Air Rarotonga', 'Cook Islands', 'GZ', 'RAR', 6, NULL),
(4248, 'Royal Air Maroc', 'Morocco', 'AT', 'RAM', 52, NULL),
(4255, 'Royal Brunei Airlines', 'Brunei', 'BI', 'RBA', 14, NULL),
(4259, 'Royal Jordanian', 'Jordan', 'RJ', 'RJA', 28, NULL),
(4264, 'Royal Nepal Airlines', 'Nepal', 'RA', 'RNA', 8, NULL),
(4270, 'Royal Phnom Penh Airways', 'Cambodia', NULL, 'PPW', 4, NULL),
(4283, 'Rusline', 'Russia', NULL, 'RLU', 22, NULL),
(4292, 'Rwandair Express', 'Rwanda', 'WB', 'RWD', 12, NULL),
(4294, 'Ryan Air Services', 'United States', NULL, 'RYA', 6, NULL),
(4295, 'Ryan International Airlines', 'United States', 'RD', 'RYN', 18, NULL),
(4296, 'Ryanair', 'Ireland', 'FR', 'RYR', 495, NULL),
(4299, 'Regional', 'France', 'YS', 'RAE', 48, NULL),
(4304, 'SATA International', 'Portugal', 'S4', 'RZO', 12, NULL),
(4305, 'South African Airways', 'South Africa', 'SA', 'SAA', 52, 'SAA South African Airways'),
(4311, 'Shaheen Air International', 'Pakistan', 'NL', 'SAI', 18, NULL),
(4319, 'Scandinavian Airlines System', 'Sweden', 'SK', 'SAS', 155, 'SAS Scandinavian Airlines'),
(4323, 'ScotAirways', 'United Kingdom', NULL, 'SAY', 6, NULL),
(4329, 'S7 Airlines', 'Russia', 'S7', 'SBI', 95, 'Sibir Airlines'),
(4335, 'Seaborne Airlines', 'United States', 'BB', 'SBS', 12, NULL),
(4342, 'Scenic Airlines', 'United States', NULL, 'SCE', 18, NULL),
(4349, 'SriLankan Airlines', 'Sri Lanka', 'UL', 'ALK', 28, NULL),
(4356, 'Sun Country Airlines', 'United States', 'SY', 'SCX', 28, NULL),
(4370, 'Southeast Air', 'United States', NULL, 'SEA', 8, NULL),
(4374, 'Sky Express', 'Greece', 'G3', 'SEH', 12, NULL),
(4375, 'Spicejet', 'India', 'SG', 'SEJ', 115, NULL),
(4388, 'Star Flyer', 'Japan', '7G', 'SFJ', 12, NULL),
(4411, 'Skagway Air Service', 'United States', 'N5', 'SGY', 6, NULL),
(4414, 'Sahara Airlines', 'Algeria', NULL, 'SHD', 8, NULL),
(4429, 'SATA Air Acores', 'Portugal', 'SP', 'SAT', 18, NULL),
(4435, 'Singapore Airlines', 'Singapore', 'SQ', 'SIA', 145, NULL),
(4436, 'Sibaviatrans', 'Russia', '5M', 'SIB', 14, NULL),
(4438, 'Skynet Airlines', 'Ireland', 'SI', 'SIH', 5, NULL),
(4454, 'Sriwijaya Air', 'Indonesia', 'SJ', 'SJY', 52, NULL),
(4455, 'Sama Airlines', 'Saudi Arabia', 'ZS', 'SMY', 12, NULL),
(4464, 'Singapore Airlines Cargo', 'Singapore', 'SQ', 'SQC', 22, NULL),
(4469, 'Siem Reap Airways', 'Cambodia', 'FT', 'SRH', 4, NULL),
(4475, 'South East Asian Airlines', 'Philippines', 'DG', 'SRQ', 8, NULL),
(4496, 'Skyservice Airlines', 'Canada', '5G', 'SSV', 18, NULL),
(4513, 'Servicios de Transportes A', 'Argentina', 'FS', 'STU', 8, NULL),
(4521, 'Sudan Airways', 'Sudan', 'SD', 'SUD', 12, NULL),
(4533, 'Saudi Arabian Airlines', 'Saudi Arabia', 'SV', 'SVA', 155, NULL),
(4547, 'Southwest Airlines', 'United States', 'WN', 'SWA', 765, NULL),
(4550, 'Southern Winds Airlines', 'Argentina', 'A4', 'SWD', 9, NULL),
(4559, 'Swiss International Air Lines', 'Switzerland', 'LX', 'SWR', 92, 'Swiss Airlines'),
(4560, 'Swissair', 'Switzerland', 'SR', 'SWR', 85, NULL),
(4563, 'Swiss European Air Lines', 'Switzerland', NULL, 'SWU', 28, 'Swiss European'),
(4564, 'Swe Fly', 'Sweden', 'WV', 'SWV', 5, NULL),
(4573, 'SunExpress', 'Turkey', 'XQ', 'SXS', 58, NULL),
(4586, 'Syrian Arab Airlines', 'Syrian Arab Republic', 'RB', 'SYR', 18, NULL),
(4589, 'Skywalk Airlines', 'United States', 'AL', 'SYX', 6, NULL),
(4599, 'Shandong Airlines', 'China', 'SC', 'CDG', 115, NULL),
(4606, 'SAS Braathens', 'Norway', NULL, 'CNO', 42, NULL),
(4607, 'Spring Airlines', 'China', '9S', 'CQH', 95, NULL),
(4608, 'Sichuan Airlines', 'China', '3U', 'CSC', 165, NULL),
(4609, 'Shanghai Airlines', 'China', 'FM', 'CSH', 125, NULL),
(4611, 'Shenzhen Airlines', 'China', 'ZH', 'CSZ', 185, NULL),
(4619, 'Sun D Or', 'Israel', '7L', 'ERO', 8, NULL),
(4620, 'SkyEurope', 'Slovakia', 'NE', 'ESK', 16, NULL),
(4640, 'Sky Europe Airlines', 'Slovakia', NULL, 'HSK', 12, NULL),
(4652, 'Spanair', 'Spain', 'JK', 'JKK', 42, NULL),
(4687, 'Spirit Airlines', 'United States', 'NK', 'NKS', 175, NULL),
(4691, 'SATENA', 'Colombia', '9R', 'NSE', 12, NULL),
(4702, 'Skywest Airlines', 'Australia', NULL, 'OZW', 18, NULL),
(4735, 'Santa Barbara Airlines', 'Venezuela', 'S3', 'BBR', 9, NULL),
(4737, 'Sky Airline', 'Chile', 'H2', 'SKU', 22, NULL),
(4738, 'SkyWest', 'United States', 'OO', 'SKW', 485, NULL),
(4739, 'Skyways Express', 'Sweden', 'JZ', 'SKX', 8, NULL),
(4740, 'Skymark Airlines', 'Japan', 'BC', 'SKY', 32, NULL),
(4750, 'SilkAir', 'Singapore', 'MI', 'SLK', 22, NULL),
(4752, 'Surinam Airways', 'Suriname', 'PY', 'SLM', 6, NULL),
(4776, 'Sterling Airlines', 'Denmark', 'NB', 'SNB', 18, NULL),
(4781, 'Skynet Asia Airways', 'Japan', '6J', 'SNJ', 12, NULL),
(4797, 'Solomon Airlines', 'Solomon Islands', 'IE', 'SOL', 5, NULL),
(4804, 'Southern Airways', 'United States', NULL, 'SOU', 22, NULL),
(4805, 'Saratov Aviation Division', 'Russia', '6W', 'SOV', 14, NULL),
(4808, 'Sat Airlines', 'Kazakhstan', 'HZ', 'SOZ', 9, NULL),
(4816, 'South Pacific Island Airways', 'United States', NULL, 'SPI', 5, NULL),
(4822, 'Shuttle America', 'United States', 'S5', 'TCF', 48, NULL),
(4840, 'Scat Air', 'Kazakhstan', 'DV', 'VSV', 18, NULL),
(4863, 'TAME', 'Ecuador', 'EQ', 'TAE', 18, NULL),
(4867, 'TAM Brazilian Airlines', 'Brazil', 'JJ', 'TAM', 165, NULL),
(4869, 'TAP Portugal', 'Portugal', 'TP', 'TAP', 95, 'TAP Air Portugal'),
(4870, 'Tunisair', 'Tunisia', 'TU', 'TAR', 32, NULL),
(4889, 'Thai Air Cargo', 'Thailand', 'T2', 'TCG', 12, NULL),
(4896, 'Thomas Cook Airlines', 'Belgium', 'FQ', 'TCW', 22, NULL),
(4897, 'Thomas Cook Airlines', 'United Kingdom', 'MT', 'TCX', 38, NULL),
(4933, 'Trigana Air Service', 'Indonesia', NULL, 'TGN', 22, NULL),
(4936, 'Tiger Airways', 'Singapore', 'TR', 'TGW', 18, NULL),
(4937, 'Tiger Airways Australia', 'Australia', 'TT', 'TGW', 12, NULL),
(4940, 'Thai Airways International', 'Thailand', 'TG', 'THA', 95, NULL),
(4946, 'Turk Hava Kurumu Hava Taksi Isletmesi', 'Turkey', NULL, 'THK', 8, NULL),
(4947, 'Thai AirAsia', 'Thailand', 'FD', 'AIQ', 68, 'Thai Air Asia'),
(4951, 'Turkish Airlines', 'Turkey', 'TK', 'THY', 365, NULL),
(4957, 'Tajikistan International Airlines', 'Tajikistan', NULL, 'TIL', 8, NULL),
(4965, 'Twin Jet', 'France', 'T7', 'TJT', 14, NULL),
(4970, 'Translift Airways', 'Ireland', NULL, 'TLA', 5, NULL),
(4981, 'Trans Mediterranean Airlines', 'Lebanon', 'TL', 'TMA', 9, NULL),
(5002, 'Tiara Air', 'Aruba', '3P', 'TNM', 4, NULL),
(5013, 'Thomsonfly', 'United Kingdom', 'BY', 'TOM', 48, NULL),
(5016, 'Tropic Air', 'Belize', 'PM', 'TOS', 12, NULL),
(5020, 'TAMPA', 'Colombia', 'QT', 'TPA', 8, NULL),
(5038, 'TransAsia Airways', 'Taiwan', 'GE', 'TNA', 28, NULL),
(5039, 'Transavia Holland', 'Netherlands', 'HV', 'TRA', 55, NULL),
(5041, 'TACV', 'Portugal', 'VR', 'TCV', 6, NULL),
(5064, 'Transwest Air', 'Canada', '9T', 'ABS', 9, NULL),
(5067, 'Transaero Airlines', 'Russia', 'UN', 'TSO', 82, NULL),
(5083, 'Turkmenistan Airlines', 'Turkmenistan', 'T5', 'TUA', 18, 'Turkmenhovayollary'),
(5085, 'Tuninter', 'Tunisia', 'UG', 'TUI', 5, NULL),
(5097, 'Travel Service', 'Czech Republic', 'QS', 'TVS', 32, NULL),
(5122, 'TUIfly Nordic', 'Sweden', '6B', 'BLX', 12, NULL),
(5133, 'TAAG Angola Airlines', 'Angola', 'DT', 'DTA', 14, NULL),
(5146, 'Turkish Air Force', 'Turkey', NULL, 'HVK', 245, NULL),
(5156, 'TAM Mercosur', 'Paraguay', 'PZ', 'LAP', 16, NULL),
(5160, 'Trans States Airlines', 'United States', 'AX', 'LOF', 48, NULL),
(5179, 'Tarom', 'Romania', 'RO', 'ROT', 28, NULL),
(5187, 'Turan Air', 'Azerbaijan', '3T', 'URN', 8, NULL),
(5188, 'TRIP Linhas A', 'Brazil', '8R', 'TIB', 18, NULL),
(5207, 'USA3000 Airlines', 'United States', 'U5', 'GWY', 12, NULL),
(5209, 'United Airlines', 'United States', 'UA', 'UAL', 825, NULL),
(5210, 'United Air Charters', 'Zimbabwe', NULL, 'UAC', 5, NULL),
(5234, 'Ural Airlines', 'Russia', 'U6', 'SVR', 48, NULL),
(5251, 'UM Airlines', 'Ukraine', 'UF', 'UKM', 8, NULL),
(5265, 'US Airways', 'United States', 'US', 'USA', 345, NULL),
(5268, 'US Helicopter', 'United States', NULL, 'USH', 18, NULL),
(5271, 'UTair Aviation', 'Russia', 'UT', 'UTA', 92, NULL),
(5279, 'United States Air Force', 'United States', NULL, 'AIO', 5425, NULL),
(5281, 'Uzbekistan Airways', 'Uzbekistan', 'HY', 'UZB', 32, NULL),
(5282, 'Ukraine International Airlines', 'Ukraine', 'PS', 'AUI', 42, NULL),
(5284, 'US Helicopter Corporation', 'United States', 'UH', NULL, 15, NULL),
(5297, 'Valuair', 'Singapore', 'VF', 'VLU', 6, NULL),
(5301, 'Vasco Air', 'Vietnam', NULL, 'VFC', 5, NULL),
(5309, 'Vietnam Airlines', 'Vietnam', 'VN', 'HVN', 95, NULL),
(5311, 'VIM Airlines', 'Russia', 'NN', 'MOV', 22, NULL),
(5325, 'Volaris', 'Mexico', 'Y4', 'VOI', 105, NULL),
(5326, 'Volga-Dnepr Airlines', 'Russia', 'VI', 'VDA', 18, NULL),
(5331, 'Virgin America', 'United States', 'VX', 'VRD', 62, NULL),
(5333, 'Virgin Express', 'Belgium', 'TV', 'VEX', 16, NULL),
(5335, 'Virgin Nigeria Airways', 'Nigeria', 'VK', 'VGN', 8, NULL),
(5347, 'Virgin Atlantic Airways', 'United Kingdom', 'VS', 'VIR', 48, NULL),
(5350, 'Viva Macau', 'Macao', 'ZG', 'VVM', 6, NULL),
(5351, 'Volare Airlines', 'Italy', 'VE', 'VLE', 9, NULL),
(5352, 'Vueling Airlines', 'Spain', 'VY', 'VLG', 125, NULL),
(5353, 'Vladivostok Air', 'Russia', 'XF', 'VLK', 22, NULL),
(5354, 'Varig Log', 'Brazil', 'LC', 'VLO', 18, NULL),
(5360, 'Virgin Australia', 'Australia', 'VA', 'VOZ', 135, NULL),
(5368, 'VRG Linhas Aereas', 'Brazil', 'RG', 'VRN', 95, 'Varig'),
(5373, 'VASP', 'Brazil', 'VP', 'VSP', 42, NULL),
(5383, 'VLM Airlines', 'Belgium', 'VG', 'VLM', 18, NULL),
(5397, 'Wayraper', 'Peru', '7W', NULL, 4, NULL),
(5399, 'WebJet Linhas A', 'Brazil', 'WJ', 'WEB', 12, NULL),
(5401, 'Welcome Air', 'Austria', '2W', 'WLC', 6, NULL),
(5411, 'West Coast Air', 'Canada', '8O', NULL, 12, NULL),
(5416, 'WestJet', 'Canada', 'WS', 'WJA', 165, NULL),
(5424, 'Western Airlines', 'United States', 'WA', 'WAL', 75, NULL),
(5439, 'Wideroe', 'Norway', 'WF', 'WIF', 48, NULL),
(5447, 'Wind Jet', 'Italy', 'IV', 'JET', 16, NULL),
(5451, 'Wings Air', 'Indonesia', 'IW', 'WON', 48, NULL),
(5461, 'Wizz Air', 'Hungary', 'W6', 'WZZ', 145, NULL),
(5462, 'Wizz Air Hungary', 'Bulgaria', '8Z', 'WVL', 8, NULL),
(5465, 'World Airways', 'United States', 'WO', 'WOA', 12, NULL),
(5479, 'XL Airways France', 'France', 'SE', 'SEU', 9, NULL),
(5484, 'Xiamen Airlines', 'China', 'MF', 'CXA', 185, NULL),
(5492, 'Yamal Airlines', 'Russia', 'YL', 'LLM', 28, NULL),
(5496, 'Yemenia', 'Yemen', 'IY', 'IYE', 12, NULL),
(5501, 'Yuzhmashavia', 'Ukraine', NULL, 'UMK', 6, NULL),
(5510, 'Zanair', 'Tanzania', NULL, 'TAN', 4, NULL),
(5523, 'Zoom Airlines', 'Canada', 'Z4', 'OOM', 8, NULL),
(5559, 'Maldivian Air Taxi', 'Maldives', '8Q', NULL, 12, NULL),
(5584, 'Sky Express', 'Russia', 'XW', 'SXR', 18, 'SkyExpress'),
(5651, 'Royal Air Cambodge', 'Cambodia', 'VJ', 'RAC', 6, NULL),
(5813, 'Air Mandalay', 'Burma', '6T', NULL, 5, NULL),
(5982, 'Air Busan', 'Republic of Korea', 'BX', 'ABL', 22, NULL),
(6196, 'Globus', 'Russia', 'GH', 'GLP', 18, NULL),
(6222, 'Air Kazakhstan', 'Kazakhstan', '9Y', 'KZK', 14, NULL),
(6557, 'Japan Air System', 'Japan', 'JD', 'JAS', 52, NULL),
(6855, 'EasyJet (DS)', 'Switzerland', 'DS', NULL, 28, NULL),
(8359, 'Star Peru (2I)', 'Peru', '2I', NULL, 8, NULL),
(8461, 'Carnival Air Lines', 'United States', 'KW', NULL, 12, NULL),
(8463, 'United Airways', 'Bangladesh', '4H', 'UBD', 6, NULL),
(8576, 'Fly540', 'Kenya', '5H', 'FFV', 9, NULL),
(8745, 'Transavia France', 'France', 'TO', 'TVF', 32, NULL),
(8809, 'Island Air (WP)', 'United States', 'WP', 'MKU', 8, NULL),
(9082, 'Uni Air', 'Taiwan', 'B7', 'UIA', 18, NULL),
(9135, 'Gomelavia', 'Belarus', 'YD', NULL, 5, NULL),
(9239, 'Red Wings', 'Russia', 'WZ', 'RWZ', 28, 'Avialinii 400'),
(9335, 'TUIfly (X3)', 'Germany', '11', NULL, 38, NULL),
(9343, 'Felix Airways', 'Yemen', 'FU', 'FXX', 5, NULL),
(9344, 'Kostromskie avialinii', 'Russia', 'K1', 'KOQ', 8, NULL),
(9373, 'Greenfly', 'Spain', 'XX', 'GFY', 4, NULL),
(9531, 'Tajik Air', 'Tajikistan', '7J', NULL, 12, NULL),
(9541, 'Air Mozambique', 'Mozambique', 'TM', NULL, 8, NULL),
(9577, 'ELK Airways', 'Estonia', NULL, 'ELK', 3, NULL),
(9620, 'Gabon Airlines', 'Gabon', 'GY', 'GBK', 6, NULL),
(9626, 'MCA Airlines', 'Sweden', NULL, 'MCA', 5, NULL),
(9656, 'Maldivo Airlines', 'Maldives', 'ML', 'MAV', 4, NULL),
(9666, 'Virgin Pacific', 'Fiji', 'VH', 'VNP', 5, NULL),
(9764, 'Zest Air', 'Philippines', 'Z2', NULL, 12, NULL),
(9784, 'Yangon Airways', 'Burma', 'HK', NULL, 6, NULL),
(9809, 'Eastar Jet', 'South Korea', 'ZE', 'ESR', 28, NULL),
(9810, 'Jin Air', 'South Korea', 'LJ', 'JNA', 38, NULL),
(9811, 'Wataniya Airways', 'Kuwait', NULL, 'KW1', 8, NULL),
(9818, 'Air Arabia Maroc', 'Morocco', '3O', NULL, 22, NULL),
(9825, 'Baltic Air lines', 'Latvia', 'B1', 'BA1', 6, NULL),
(9828, 'Ciel Canadien', 'Canada', 'YC', 'YCC', 5, NULL),
(9829, 'Canadian National Airways', 'Canada', 'CN', 'YCP', 8, NULL),
(9833, 'Epic Holiday', 'United States', 'FA', '4AA', 4, 'Epic Holidays'),
(9838, 'Indochina Airlines', 'Vietnam', NULL, 'AXC', 6, NULL),
(9851, 'Air Comet Chile', 'Chile', '3I', NULL, 8, NULL),
(9859, 'German Air Force - FLB', 'Germany', NULL, 'FLB', 85, NULL),
(10114, 'Line Blue', 'Germany', 'L8', 'LBL', 5, NULL),
(10117, 'FlyLAL Charters', 'Lithuania', NULL, 'LLC', 4, NULL),
(10122, 'Salzburg arrows', 'Austria', 'SZ', NULL, 6, 'SZA'),
(10123, 'Texas Wings', 'United States', 'TQ', 'TXW', 6, NULL),
(10128, 'Dennis Sky', 'Israel', 'DH', 'DSY', 8, 'Dennis Sky Holding'),
(10224, 'Zz', 'Belgium', 'ZZ', NULL, 3, NULL),
(10226, 'Atifly', 'United States', 'A1', 'A1F', 4, NULL),
(10371, 'Aerolineas heredas santa maria', 'Dominican Republic', NULL, 'SZB', 4, NULL),
(10372, 'Ciao Air', 'Italy', '99', NULL, 5, NULL),
(10642, 'Jc royal.britannica', 'United Kingdom', NULL, 'JRB', 4, NULL),
(10650, 'Pal airlines', 'Chile', '5P', NULL, 5, NULL),
(10673, 'CanXpress', 'Canada', 'C1', 'CA1', 6, NULL),
(10674, 'Danube Wings (V5)', 'Slovakia', 'V5', NULL, 8, NULL),
(10675, 'Sharp Airlines', 'Australia', 'SH', 'SHA', 9, NULL),
(10683, 'CanXplorer', 'Canada', 'C2', 'CAP', 5, NULL),
(10715, 'Click (Mexicana)', 'Mexico', 'QA', NULL, 8, NULL),
(10735, 'World Experience Airline', 'Canada', 'W1', 'WE1', 5, 'WEA'),
(10737, 'ALAK', 'Russia', 'J4', NULL, 6, NULL),
(10739, 'Air Choice One', 'United States', '3E', NULL, 9, NULL),
(10740, 'Tianjin Airlines', 'China', NULL, 'GCR', 68, NULL),
(10741, 'China United', 'China', 'KN', NULL, 48, NULL),
(10748, 'Locair', 'United States', 'ZQ', 'LOC', 5, NULL),
(10758, 'Safi Airlines', 'Afghanistan', '4Q', NULL, 6, NULL),
(10765, 'SeaPort Airlines', 'United States', 'K5', 'SQH', 12, NULL),
(10776, 'Salmon Air', 'United States', 'S6', NULL, 4, NULL),
(10798, 'Bobb Air Freight', 'Germany', '1', NULL, 6, NULL),
(10800, 'Star1 Airlines', 'Lithuania', 'V9', 'HCW', 5, NULL),
(10845, 'Pelita', 'Indonesia', '6D', NULL, 12, NULL),
(10912, 'Alaska Seaplane Service', 'United States', 'J5', NULL, 8, NULL),
(10945, 'Enerjet', 'Canada', NULL, 'ENJ', 6, NULL),
(10955, 'MexicanaLink', 'Mexico', 'I6', 'MXI', 18, NULL),
(10960, 'Island Spirit', 'Iceland', 'IP', 'ISX', 4, NULL),
(10969, 'TACA Peru', 'Peru', 'T0', NULL, 12, NULL),
(11700, 'Orbest', 'Portugal', NULL, 'OBS', 8, NULL),
(11719, 'Southern Air Charter', 'Bahamas', NULL, 'SOA', 5, NULL),
(11724, 'SVG Air', 'Saint Vincent and the Grenadines', NULL, 'SVG', 4, NULL),
(11726, 'Air Century', 'Dominican Republic', NULL, 'CEY', 6, NULL),
(11731, 'Pan Am World Airways Dominicana', 'Dominican Republic', '7Q', NULL, 8, 'PAWA Dominicana'),
(11732, 'Primera Air', 'Iceland', 'PF', NULL, 8, NULL),
(11741, 'Air Antilles Express', 'Guadeloupe', '3S', NULL, 6, NULL),
(11751, 'Sol Lineas Aereas', 'Argentina', NULL, 'OLS', 8, NULL),
(11755, 'Regional Paraguaya', 'Paraguay', 'P7', 'REP', 6, NULL),
(11761, 'VIP Ecuador', 'Ecuador', 'V6', NULL, 5, NULL),
(11762, 'Transportes Aereos Cielos Andinos', 'Peru', NULL, 'NDN', 5, NULL),
(11763, 'Peruvian Airlines', 'Peru', 'P9', NULL, 12, NULL),
(11765, 'EasyFly', 'Colombia', NULL, 'EFY', 14, NULL),
(11767, 'Polar Airlines', 'Russia', NULL, NULL, 8, NULL),
(11794, 'Catovair', 'Mauritius', 'OC', NULL, 4, NULL),
(11795, 'Andalus Lineas Aereas', 'Spain', NULL, 'ANU', 5, NULL),
(11798, 'Air 26', 'Angola', NULL, 'DCD', 4, NULL),
(11800, 'Mauritania Airways', 'Mauritania', NULL, 'MTW', 4, NULL),
(11802, 'CEIBA Intercontinental', 'Equatorial Guinea', NULL, 'CEL', 5, NULL),
(11804, 'Halcyonair', 'Cape Verde', '7Z', NULL, 4, NULL),
(11805, 'Business Aviation', 'Congo (Kinshasa)', '4P', NULL, 3, NULL),
(11806, 'Compagnie Africaine d Aviation', 'Congo (Kinshasa)', 'E9', NULL, 6, NULL),
(11808, 'Zambia Skyways', 'Zambia', 'K8', NULL, 4, NULL),
(11811, 'AlMasria Universal Airlines', 'Egypt', 'UJ', 'LMU', 8, NULL),
(11813, 'EgyptAir Express', 'Egypt', NULL, 'MSE', 18, NULL),
(11814, 'SmartLynx Airlines', 'Latvia', '6Y', NULL, 22, NULL),
(11815, 'Air Italy Egypt', 'Egypt', NULL, 'EUD', 6, NULL),
(11816, 'KoralBlue Airlines', 'Egypt', 'K7', 'KBR', 5, NULL),
(11820, 'Wind Rose Aviation', 'Ukraine', NULL, 'WRC', 12, NULL),
(11823, 'Elysian Airlines', 'Cameroon', 'E4', 'GIE', 5, NULL),
(11833, 'Sevenair', 'Tunisia', NULL, 'SEN', 4, NULL),
(11834, 'Hellenic Imperial Airways', 'Greece', 'HT', 'IMP', 6, NULL),
(11836, 'Amsterdam Airlines', 'Netherlands', 'WD', 'AAN', 5, NULL),
(11838, 'Arik Niger', 'Niger', 'Q9', 'NAK', 4, NULL),
(11839, 'Dana Air', 'Nigeria', 'DA', NULL, 12, NULL),
(11840, 'STP Airways', 'Sao Tome and Principe', '8F', 'STP', 3, NULL),
(11843, 'Med Airways', 'Lebanon', '7Y', NULL, 5, NULL),
(11850, 'Skyjet Airlines', 'Uganda', 'UQ', 'SJU', 6, NULL),
(11855, 'Air Volga', 'Russia', 'G6', NULL, 8, NULL),
(11856, 'Transavia Denmark', 'Denmark', NULL, 'TDK', 6, NULL),
(11857, 'Royal Falcon', 'Jordan', 'RL', 'RFJ', 8, NULL),
(11873, 'Euroline', 'Georgia', '4L', 'MJX', 5, NULL),
(11943, 'Turkuaz Airlines', 'Turkey', NULL, 'TRK', 8, NULL),
(11947, 'Athens Airways', 'Greece', 'ZF', NULL, 6, NULL),
(11948, 'Viking Hellas', 'Greece', 'VQ', 'VKH', 5, NULL),
(11949, 'Norlandair', 'Iceland', NULL, 'FNA', 4, NULL),
(11950, 'Flugfelag Vestmannaeyja', 'Iceland', NULL, 'FVM', 3, NULL),
(11963, 'Starline.kz', 'Kazakhstan', 'DZ', NULL, 6, NULL),
(12960, 'Lugansk Airlines', 'Ukraine', 'L7', NULL, 6, NULL),
(12961, 'Gryphon Airlines', 'United States', '6P', NULL, 8, NULL),
(12962, 'Gadair European Airlines', 'Spain', 'GP', 'GDR', 6, NULL),
(12965, 'Spirit of Manila Airlines', 'Philippines', 'SM', 'MNP', 8, NULL),
(12975, 'Chongqing Airlines', 'China', 'OQ', 'CQN', 58, NULL),
(12976, 'Grand China Air', 'China', NULL, 'GDC', 45, NULL),
(12978, 'West Air China', 'China', 'PN', 'CHB', 52, NULL),
(12997, 'QatXpress', 'Qatar', 'C3', 'QAX', 6, 'qatXpress'),
(13076, 'OneChina', 'China', '1C', '1CH', 28, 'OneChina'),
(13088, 'NordStar Airlines', 'Russia', 'Y7', NULL, 18, NULL),
(13089, 'Joy Air', 'China', 'JR', 'JOY', 22, NULL),
(13105, 'Air India Regional', 'India', 'CD', NULL, 48, NULL),
(13106, 'MDLR Airlines', 'India', '9H', NULL, 6, NULL),
(13107, 'Jagson Airlines', 'India', NULL, 'JGN', 8, NULL),
(13108, 'Maldivian', 'Maldives', 'Q2', NULL, 10, NULL),
(13130, 'Xpressair', 'Indonesia', 'XN', NULL, 12, NULL),
(13178, 'Strategic Airlines', 'Australia', 'VC', NULL, 8, NULL),
(13181, 'Fars Air Qeshm', 'Iran', NULL, 'QFZ', 6, NULL),
(13187, 'Eastok Avia', 'Kyrgyzstan', NULL, 'EAA', 5, NULL),
(13188, 'Jupiter Airlines', 'United Arab Emirates', NULL, 'JPU', 8, NULL),
(13189, 'Vision Air International', 'Pakistan', NULL, 'VIS', 6, NULL),
(13190, 'Al-Naser Airlines', 'Iraq', 'NA', NULL, 5, NULL),
(13200, 'Fuji Dream Airlines', 'Japan', 'JH', NULL, 14, NULL),
(13202, 'Korea Express Air', 'South Korea', NULL, 'KEA', 12, NULL),
(13209, 'Eznis Airways', 'Mongolia', NULL, 'EZA', 4, NULL),
(13211, 'Pacific Flier', 'Palau', NULL, 'PFL', 3, NULL),
(13217, 'Syrian Pearl Airlines', 'Syria', NULL, 'PSB', 4, NULL),
(13218, 'SGA Airlines', 'Thailand', '5E', NULL, 8, NULL),
(13242, 'Air2there', 'New Zealand', 'F8', NULL, 5, NULL),
(13254, 'Avianova (Russia)', 'Russia', 'AO', NULL, 12, NULL),
(13303, 'Parmiss Airlines (IPV)', 'Iran', 'PA', 'IPV', 8, NULL),
(13304, 'EuropeSky', 'Germany', 'ES', 'EUV', 5, NULL),
(13306, 'BRAZIL AIR', 'Brazil', 'GB', 'BZE', 8, 'BRAZIL AIR'),
(13335, 'Homer Air', 'Germany', 'MR', 'OME', 4, 'Homer Sky'),
(13391, 'U.S. Air', 'United States', '-+', '--+', 6, NULL),
(13394, 'Jayrow', 'Australia', NULL, NULL, 3, NULL),
(13397, 'Wilderness Air', 'Australia', ';;', NULL, 4, NULL),
(13398, 'Whitaker Air', 'Australia', '^^', NULL, 3, NULL),
(13633, 'PanAm World Airways', 'United States', 'WQ', 'PQW', 8, NULL),
(13690, 'Virginwings', 'Germany', 'YY', 'VWA', 5, NULL),
(13704, 'KSY', 'Greece', 'KY', 'KSY', 5, 'Kreta Sky'),
(13732, 'Buquebus Lineas Aereas', 'Uruguay', 'BQ', 'BQB', 6, NULL),
(13734, 'SOCHI AIR', 'Russia', 'CQ', 'KOL', 12, 'SOCHI'),
(13757, 'Wizz Air Ukraine', 'Ukraine', 'WU', 'WAU', 18, NULL),
(13781, '88', 'Cyprus', '47', 'VVN', 4, NULL),
(13815, 'LCM AIRLINES', 'Russia', 'LQ', 'LMM', 8, NULL),
(13899, 'Cambodia Angkor Air (K6)', 'Cambodia', 'K6', NULL, 10, NULL),
(13936, 'Royal European Airlines', 'United Kingdom', '69', NULL, 5, NULL),
(13947, 'Toms and co airliners', 'France', '&T', 'T&O', 4, 'Toms air'),
(13983, 'Azul', 'Brazil', 'AD', 'AZU', 155, 'Azul Linhas Aereas Brasileiras'),
(14061, 'LSM Airlines', 'Russia', 'PQ', 'LOO', 8, 'slowbird'),
(14069, 'Zapolyarie Airlines', 'Russia', NULL, 'PZY', 12, 'Zapolyarye Airlines'),
(14073, 'Finlandian', 'Finland', NULL, 'FN1', 5, NULL),
(14094, 'LionXpress', 'Cameroon', 'C4', 'LIX', 5, 'lionXpress'),
(14118, 'Genesis', 'Pakistan', 'GK', NULL, 6, NULL),
(14388, 'Congo Express', 'Congo (Kinshasa)', 'XZ', NULL, 4, NULL),
(14485, 'Fly Dubai', 'United Arab Emirates', 'FZ', 'FDB', 75, NULL),
(14620, 'Domenican Airlines', 'Dominican Republic', 'D1', 'MDO', 5, 'Domenican'),
(14679, 'ConneX European Airline', 'Austria', NULL, '2CO', 5, NULL),
(14849, 'Aereonautica militare', 'Italy', 'JY', 'AXZ', 95, NULL),
(14858, 'Kal Star Aviation', 'Indonesia', NULL, 'KLS', 12, NULL),
(14881, 'LSM AIRLINES', 'Russia', 'YZ', 'YZZ', 8, 'Russian. Yours Air Lines'),
(15814, 'UTair-Express', 'Russia', 'UR', NULL, 28, NULL),
(15837, 'Huaxia', 'China', 'G5', NULL, 32, 'HUAXIA'),
(15867, 'Zabaykalskii Airlines', 'Russia', 'ZP', 'ZZZ', 10, 'Baikal Airlines'),
(15887, 'CBM America', 'United States', NULL, 'XBM', 6, NULL),
(15893, 'Marysya Airlines', 'Russia', 'M4', '1QA', 6, 'MARYSYA AIRLINES'),
(15897, 'N1', 'Peru', 'N1', NULL, 5, NULL),
(15930, 'Airlink (SAA)', 'South Africa', '4Z', NULL, 22, NULL),
(15939, 'Westfalia Express VA', 'Germany', NULL, 'WFX', 5, NULL),
(15953, 'JobAir', 'Czech Republic', '3B', NULL, 5, NULL),
(15975, 'Black Stallion Airways', 'United States', 'BZ', 'BSA', 5, NULL),
(15984, 'German International Air Lines', 'Germany', 'GM', 'GER', 6, 'Germanair'),
(15985, 'TrasBrasil', 'Brazil', 'TB', 'TBZ', 8, NULL),
(15989, 'TransBrasil Airlines', 'Brazil', 'TH', 'THS', 12, NULL),
(15999, 'China SSS', 'China', '9C', NULL, 28, 'Chunqiu Airlines'),
(16084, 'AIR INDOCHINE', 'Vietnam', NULL, 'IIA', 6, NULL),
(16100, 'Happy Air', 'Thailand', NULL, 'HPY', 5, NULL),
(16101, 'Solar Air', 'Thailand', NULL, 'SRB', 4, NULL),
(16103, 'Air Mekong', 'Vietnam', 'P8', 'MKG', 8, NULL),
(16110, 'Harbour Air (Priv)', 'Canada', 'H3', NULL, 12, NULL),
(16116, 'Air Hamburg (AHO)', 'Germany', 'HH', 'AHO', 5, NULL),
(16120, 'ZABAIKAL AIRLINES', 'Russia', 'Z6', 'ZTT', 8, 'ZABAIKAL'),
(16127, 'TransHolding', 'Brazil', 'TI', 'THI', 8, 'Trans'),
(16130, 'SUR Lineas Aereas', 'Argentina', NULL, 'SZZ', 6, NULL),
(16131, 'Aerolineas Africanas', 'Guinea', NULL, 'AA1', 4, NULL),
(16133, 'Yeti Airways', 'Nepal', 'YT', NULL, 8, NULL),
(16135, 'Yellowstone Club Private Shuttle', 'United States', 'Y1', NULL, 3, NULL),
(16136, 'Caucasus Airlines', 'Georgia', 'NS', NULL, 5, NULL),
(16139, 'Serbian Airlines', 'Serbia', 'S1', 'SA1', 6, NULL),
(16149, 'Windward Islands Airways', 'Netherlands Antilles', 'WM', NULL, 5, NULL),
(16150, 'TransHolding System', 'Brazil', 'YO', 'TYS', 6, NULL),
(16151, 'CCML Airlines', 'Colombia', 'CB', 'CCC', 6, NULL),
(16198, 'Small Planet Airlines', 'Lithuania', NULL, 'ELC', 18, NULL),
(16234, 'Fly Brasil', 'Brazil', 'F1', 'FBL', 8, 'Fly Brasil'),
(16261, 'CB Airways UK ( Interliging Flights )', 'United Kingdom', '1F', 'CIF', 4, NULL),
(16262, 'Fly Colombia ( Interliging Flights )', 'Colombia', '3F', '3FF', 5, NULL),
(16264, 'Trans Pas Air', 'United States', 'T6', 'TP6', 5, NULL),
(16273, 'KMV', 'Russia', NULL, NULL, 6, NULL),
(16323, 'Himalayan Airlines', 'Nepal', 'HC', 'HYM', 6, 'Himalaya'),
(16327, 'Indya Airline Group', 'India', 'G1', 'IG1', 8, 'Indya1'),
(16329, 'Sunwing', 'Canada', 'WG', NULL, 42, NULL),
(16358, 'Turkish Wings Domestic', 'Turkey', NULL, 'TWD', 12, NULL),
(16359, 'Japan Regio', 'Japan', 'ZX', 'ZXY', 10, NULL),
(16362, 'OCEAN AIR CARGO', 'India', NULL, 'IXO', 8, NULL),
(16363, 'Norte Lineas Aereas', 'Argentina', 'N0', NULL, 6, 'NORTE'),
(16364, 'Austral Brasil', 'Brazil', 'W7', NULL, 8, 'Austral Brasil lineas aereas'),
(16373, 'PEGASUS AIRLINES-', 'Turkey', 'H9', NULL, 12, NULL),
(16409, 'Nihon.jet connect', 'Kyrgyzstan', NULL, 'NX1', 5, NULL),
(16415, 'Camair-co', 'Cameroon', 'QC', NULL, 6, NULL),
(16459, 'Sky Regional', 'Canada', 'RS', 'SKV', 28, 'Air Canada Express'),
(16507, 'LSM International', 'Russia', 'II', 'UWW', 8, 'Moskva-air'),
(16508, 'Baikotovitchestrian Airlines', 'American Samoa', 'BU', 'BUU', 3, NULL),
(16511, 'Luchsh Airlines', 'Russia', 'L4', 'LJJ', 6, 'Air luch'),
(16556, 'ENTERair', 'Poland', NULL, 'QQQ', 6, NULL),
(16585, 'Air Cargo Germany', 'Germany', '6U', NULL, 8, NULL),
(16615, 'Mongolian International Air Lines', 'Mongolia', '7M', 'ZTF', 8, 'Mongol Air'),
(16624, 'Tway Airlines', 'South Korea', 'TW', 'TWB', 28, NULL),
(16625, 'Papillon Grand Canyon Helicopters', 'United States', 'HI', NULL, 18, NULL),
(16628, 'Jusur airways', 'Egypt', 'JX', 'JSR', 6, NULL),
(16645, 'NEXT Brasil', 'Brazil', 'XB', 'NXB', 8, 'NEXT'),
(16660, 'AeroWorld', 'Russia', 'W4', 'WER', 8, 'Sovet Air'),
(16695, 'GNB Linhas Aereas', 'Brazil', 'GN', NULL, 6, NULL),
(16702, 'Usa Sky Cargo', 'United States', 'E1', 'ES2', 6, 'USky'),
(16707, 'Hankook Airline', 'South Korea', 'HN', 'HNX', 12, NULL),
(16717, 'REDjet', 'Barbados', 'Z7', NULL, 4, NULL),
(16720, 'Red Jet Andes', 'Peru', 'PT', NULL, 5, NULL),
(16721, 'Red Jet Canada', 'Canada', 'QY', NULL, 5, NULL),
(16723, 'Sprintair', 'Poland', NULL, 'SRN', 12, NULL),
(16724, 'Red Jet Mexico', 'Mexico', '4X', NULL, 5, NULL),
(16725, 'Marusya Airways', 'Russia', 'Y8', 'MRS', 6, 'Marusya Air'),
(16726, 'Era Alaska', 'United States', '7H', 'ERR', 18, NULL),
(16728, 'AirRussia', 'Russia', 'R8', 'RRJ', 8, 'RussianConector'),
(16735, 'Hankook Air US', 'United States', 'H1', 'HA1', 6, NULL),
(16794, 'Carpatair Flight Training', 'Romania', NULL, 'SMW', 6, NULL),
(16796, 'I-Fly', 'Russia', 'H5', 'RSY', 22, NULL),
(16826, 'Whitejets', 'Brazil', NULL, 'WTJ', 5, NULL),
(16837, 'VickJet', 'France', 'KT', 'VKJ', 5, NULL),
(16844, 'BVI Airways', 'British Virgin Islands', 'XV', NULL, 3, NULL),
(16858, 'Hamburg Airways', 'Germany', NULL, 'HAY', 5, NULL),
(16860, 'Salsa d Haiti', 'Haiti', 'SO', 'SLC', 4, NULL),
(16867, 'Zambezi Airlines (ZMA)', 'Zambia', 'ZJ', NULL, 4, NULL),
(16868, 'Kan Air', 'Thailand', NULL, 'KND', 8, NULL),
(16881, 'Air Cudlua', 'United Kingdom', NULL, 'CUD', 4, 'Air Cudlua'),
(16882, 'Polet Airlines (Priv)', 'Russia', 'YQ', NULL, 6, NULL),
(16895, 'Air Explore', 'Slovakia', NULL, 'AXE', 5, NULL),
(16901, '12 North', 'India', '12', 'N12', 6, NULL),
(16919, 'Holidays Czech Airlines', 'Czech Republic', NULL, 'HCC', 5, NULL),
(16921, 'Comtel Air', 'Austria', NULL, 'COE', 4, NULL),
(16926, 'Mint Airways', 'Spain', NULL, 'MIC', 5, NULL),
(16932, 'Orbit Airlines', 'United States', NULL, 'OBT', 6, 'Orbit'),
(16939, 'Air Bucharest', 'Romania', NULL, 'BUR', 5, NULL),
(16940, 'AlbaStar', 'Spain', NULL, 'LAV', 8, NULL),
(16942, 'Mauritania Airlines International', 'Mauritania', 'L6', 'MAI', 6, NULL),
(16956, 'MAT Airways', 'Macedonia', '6F', 'MKD', 6, NULL),
(16960, 'Asian Wings Airways', 'Burma', 'AW', 'AWM', 8, NULL),
(16963, 'Air Arabia Egypt', 'Egypt', 'E5', 'RBG', 18, NULL),
(16967, 'Eagles Airlines', 'Italy', NULL, 'EGS', 5, NULL),
(16973, 'YES Airways', 'Poland', NULL, 'YEP', 5, NULL),
(16975, 'Alitalia Cityliner', 'Italy', 'CT', NULL, 22, NULL),
(16983, 'Direct Aero Services', 'Romania', NULL, 'DSV', 5, NULL),
(16985, 'Medallion Air', 'Romania', NULL, 'MDP', 4, NULL),
(17022, 'Orchid Airlines', 'Australia', 'OI', 'ORC', 5, NULL),
(17023, 'Asia Wings', 'Kazakhstan', 'Y5', 'AWA', 6, NULL),
(17026, 'Georgian International Airlines', 'Georgia', NULL, 'GNN', 5, NULL),
(17027, 'Air Batumi', 'Georgia', NULL, 'BTM', 4, NULL),
(17082, 'Skywest Australia', 'Australia', 'XR', NULL, 12, NULL),
(17083, 'Nile Air', 'Egypt', 'NP', 'NIA', 12, NULL),
(17086, 'Feeder Airlines', 'Sudan', NULL, 'FDD', 5, NULL),
(17094, 'Senegal Airlines', 'Senegal', 'DN', 'SGG', 8, NULL),
(17095, 'Fly 6ix', 'Sierra Leone', '6I', NULL, 3, NULL),
(17099, 'Starbow Airlines', 'Ghana', 'S9', NULL, 8, NULL),
(17115, 'Copenhagen Express', 'Denmark', '0X', 'CX0', 6, NULL),
(17408, 'BusinessAir', 'Thailand', '8B', 'BCC', 8, NULL),
(17519, 'SENIC AIRLINES', 'United States', 'YR', NULL, 5, NULL),
(17563, 'XOJET', 'United States', NULL, 'XOJ', 12, NULL),
(17571, 'Sky Wing Pacific', 'South Korea', 'C7', 'CR7', 8, NULL),
(17572, 'Bateleur Air', 'South Africa', NULL, 'BEU', 6, NULL),
(17574, 'Air Indus', 'Pakistan', 'PP', 'AI0', 8, 'Indus Airlines Pak'),
(17628, 'Orbit International Airlines', 'United States', NULL, 'OAI', 5, NULL),
(17629, 'Orbit Regional Airlines', 'United States', NULL, 'OAR', 5, NULL),
(17630, 'Orbit Atlantic Airways', 'United States', NULL, 'OAN', 5, NULL),
(17658, 'Volotea', 'Spain', NULL, 'VOO', 38, NULL),
(17675, 'Peach Aviation', 'Japan', 'MM', NULL, 38, NULL),
(17694, 'Helitt Lineas Aereas', 'Spain', NULL, 'HTH', 6, NULL),
(17695, 'Russia State Transport', 'Russia', NULL, 'RSD', 45, 'Federal State Budget Inst'),
(17726, 'Malaysia Wings', 'Malaysia', NULL, 'MWI', 12, NULL),
(17750, 'Aviabus', 'Russia', 'U1', 'ABI', 8, NULL),
(17780, 'Michael Airlines', 'Puerto Rico', 'DF', 'MJG', 4, 'Javi'),
(17786, 'Korongo Airlines', 'Congo (Kinshasa)', 'ZC', 'KGO', 4, NULL),
(17794, 'Indonesia Sky', 'Indonesia', 'I5', 'IDS', 8, NULL),
(17841, 'Aws express', 'United States', 'B0', '666', 4, NULL),
(17859, 'Southjet', 'United States', '76', 'SJS', 5, NULL),
(17860, 'Southjet connect', 'United States', '77', 'ZCS', 5, NULL),
(17862, 'Southjet cargo', 'United States', '78', 'XAN', 5, NULL),
(17881, 'Iberia Express', 'Spain', 'I2', 'IBS', 42, NULL),
(17885, 'Interjet (ABC Aerolineas)', 'Mexico', '4O', NULL, 95, NULL),
(17889, 'AirOnix', 'Ukraine', 'OG', NULL, 6, NULL),
(17890, 'Nordic Global Airlines', 'Finland', 'NJ', 'NGB', 8, NULL),
(17891, 'Scoot', 'Singapore', 'TZ', 'SCO', 55, NULL),
(17909, 'Hi Fly (5K)', 'Portugal', '5K', NULL, 12, NULL),
(17911, 'China Northwest Airlines (WH)', 'China', 'WH', NULL, 28, NULL),
(17935, 'Zenith International Airline', 'Thailand', 'ZN', 'ZNA', 10, 'Zenith'),
(17936, 'Orbit Airlines Azerbaijan', 'Azerbaijan', 'O1', 'OAB', 6, 'Orbit Azerbaijan'),
(17989, 'Air Alps Aviation (A6)', 'Austria', 'A6', NULL, 5, NULL),
(18076, 'Flying kangaroo Airline', 'Australia', NULL, 'FKA', 5, 'Skippy'),
(18083, 'RusJet', 'Russia', NULL, 'RSJ', 8, NULL),
(18118, 'VietJet Air', 'Vietnam', NULL, 'VJC', 85, 'VietJet'),
(18169, 'Patriot Airways', 'United States', 'P4', NULL, 5, NULL),
(18178, 'Vision Airlines (V2)', 'United States', 'V2', 'RBY', 6, NULL),
(18232, 'BQB Lineas Aereas', 'Uruguay', '5Q', NULL, 6, 'Buquebus'),
(18237, 'AirAsia Japan', 'Japan', NULL, 'WAJ', 12, NULL),
(18239, 'Yellowtail', 'United States', 'YE', 'YEL', 4, NULL),
(18241, 'Royal Airways', 'United States', 'KG', 'RAW', 5, 'Royal Inc.'),
(18252, 'FlyHigh Airlines Ireland (FH)', 'Ireland', 'FH', 'FHI', 5, NULL),
(18257, 'Executive AirShare', 'United States', NULL, 'XSR', 12, NULL),
(18475, 'Hebei Airlines', 'China', NULL, 'HBH', 28, NULL),
(18476, 'Air KBZ', 'Burma', NULL, 'KBZ', 8, NULL),
(18477, 'Aero VIP (2D)', 'Portugal', '2D', NULL, 5, NULL),
(18497, 'Yangon Airways Ltd.', 'Burma', 'YH', NULL, 6, NULL),
(18529, 'T.J. Air', 'United States', 'TJ', 'TJA', 5, NULL),
(18543, 'SkyWork Airlines', 'Switzerland', 'SX', NULL, 8, NULL),
(18553, 'Maastricht Airlines', 'Netherlands', 'W2', NULL, 5, NULL),
(18617, 'Euro Jet', 'Germany', '24', NULL, 5, NULL),
(18621, 'Ukraine Atlantic', 'Ukraine', NULL, 'UAT', 6, NULL),
(18668, 'Nesma Airlines', 'Egypt', NULL, 'NMA', 8, NULL),
(18672, 'East Horizon', 'Afghanistan', NULL, 'EHN', 4, NULL),
(18676, 'Air Majoro', 'Peru', NULL, 'MJP', 4, NULL),
(18692, 'Rotana Jet', 'United Arab Emirates', NULL, 'RJD', 8, NULL),
(18700, 'SOCHI AIR CHATER', 'Russia', 'Q3', 'QER', 8, 'Sochi Air'),
(18702, 'Denim Air', 'Norway', 'J7', NULL, 6, 'FlyNonstop'),
(18732, 'Malindo Air', 'Malaysia', 'OD', 'MXD', 42, NULL),
(18781, 'Hermes Airlines', 'Greece', NULL, 'HRM', 5, NULL),
(18825, 'Flightlink Tanzania', 'Tanzania', 'Z9', NULL, 6, 'Flightlink'),
(18828, 'IzAvia', 'Russia', 'I8', NULL, 8, NULL),
(18860, 'Russian Airline 18860', 'Russia', NULL, NULL, 6, NULL),
(18863, 'Russian Airline 18863', 'Russia', NULL, 'PKV', 8, 'PKV Airlines'),
(18930, 'Maryland Air', 'United States', 'M1', 'M1F', 5, 'Maryland'),
(18944, 'Insel Air (7I/INC) (Priv)', 'Netherlands Antilles', '7I', NULL, 5, NULL),
(18946, 'VivaColombia', 'Colombia', '5Z', 'VVC', 38, NULL),
(18952, 'Flybe Finland Oy', 'Finland', NULL, 'FCM', 8, NULL),
(18959, 'Bingo Airways', 'Poland', NULL, 'BGY', 5, 'Bingo'),
(19007, 'Bluebird Airways (BZ)', 'Greece', NULL, 'BBG', 5, NULL),
(19016, 'Apache Air', 'United States', 'ZM', 'IWA', 6, 'Apache'),
(19026, 'MHS Aviation GmbH', 'Germany', 'M2', NULL, 4, NULL),
(19030, 'Jettor Airlines', 'Hong Kong', 'NR', 'JTO', 8, 'Jettor'),
(19215, 'Flyme (VP)', 'Maldives', NULL, 'VQI', 8, NULL),
(19225, 'Thai Lion Air', 'Thailand', 'SL', NULL, 42, NULL),
(19244, 'Golden Myanmar Airlines', 'Burma', NULL, 'GMR', 6, NULL),
(19276, 'Canaryfly', 'Spain', NULL, 'CNF', 8, NULL),
(19280, 'Sunrise Airways', 'Haiti', NULL, 'KSZ', 5, NULL),
(19287, 'National Air Cargo', 'United States', 'N8', 'NCR', 18, NULL),
(19290, 'Eastern Atlantic Virtual Airlines', 'United States', '13', 'EAV', 3, NULL),
(19305, 'Citilink Indonesia', 'Indonesia', 'QG', NULL, 48, NULL),
(19337, 'Transair', 'Canada', NULL, 'TTZ', 12, NULL),
(19350, 'Comfort Express Virtual Charters Albany', 'United States', NULL, 'EVC', 3, NULL),
(19351, 'Comfort Express Virtual Charters', 'United States', NULL, 'CEO', 3, NULL),
(19359, 'FLYJET', 'Poland', NULL, 'FYJ', 5, NULL),
(19361, 'Snowbird Airlines', 'Finland', 'S8', 'SBD', 6, NULL),
(19363, 'Russkie Krylya', 'Russia', NULL, 'KRY', 8, NULL),
(19367, 'Kharkiv Airlines', 'Ukraine', 'KH', 'KHK', 6, NULL),
(19433, 'XAIR USA', 'United States', 'XA', 'XAU', 5, NULL),
(19451, 'Air Costa', 'India', 'LB', NULL, 12, NULL),
(19459, 'Simrik Airlines', 'Nepal', NULL, 'RMK', 5, NULL),
(19473, 'XPTO', 'Portugal', 'XP', 'XPT', 4, 'XPTO'),
(19474, 'Royal Flight', 'Russia', NULL, 'DME', 12, NULL),
(19525, 'BBN-Airways', 'United Kingdom', NULL, 'EGH', 5, 'BlackBurn'),
(19531, 'Tomsk-Avia', 'Russia', NULL, 'TKS', 8, NULL),
(19541, 'Malawian Airlines', 'Malawi', '3W', NULL, 6, NULL),
(19548, 'Yeti Airlines', 'Nepal', NULL, 'NYT', 6, NULL),
(19567, 'Avilu', 'Switzerland', NULL, NULL, 4, 'Avilu SA'),
(19582, 'Air Serbia', 'Serbia', 'JU', 'ASL', 22, NULL),
(19599, 'Skyline Ulasim Ticaret A.S.', 'Turkey', NULL, 'KCU', 6, 'Skyline Ulasim Ticaret A.S.'),
(19610, 'Air Lituanica', 'Lithuania', 'LT', 'LTU', 8, 'Air Lituanica'),
(19619, 'Envoy Air', 'United States', NULL, 'ENY', 185, NULL),
(19651, 'CARICOM AIRWAYS (BARBADOS) INC.', 'Barbados', NULL, 'CCB', 4, 'CARICOM AIRWAYS'),
(19674, 'Rainbow Air (RAI)', 'United States', 'RN', 'RAB', 5, 'Rainbow Air (RAI)'),
(19675, 'Rainbow Air Canada', 'Canada', 'RY', 'RAY', 5, 'Rainbow Air CAN'),
(19676, 'Rainbow Air Polynesia', 'United States', 'RX', 'RPO', 4, 'Rainbow Air POL'),
(19677, 'Rainbow Air Euro', 'United Kingdom', 'RU', 'RUE', 5, 'Rainbow Air EU'),
(19678, 'Rainbow Air US', 'United States', 'RM', 'RNY', 5, 'Rainbow Air US'),
(19745, 'Transilvania', 'Romania', NULL, 'TNS', 5, NULL),
(19751, 'Dobrolet', 'Russia', 'QD', 'DOB', 8, 'Dobrolet Airlines'),
(19774, 'Spike Airlines', 'United States', 'S0', 'SAL', 5, 'Aero Spike'),
(19776, 'Grand Cru Airlines', 'Lithuania', NULL, 'GCA', 5, NULL),
(19785, 'Go2Sky', 'Slovakia', NULL, 'RLX', 6, NULL),
(19803, 'All Argentina', 'Argentina', 'L1', 'AL1', 6, 'All Argentina'),
(19804, 'All America', 'United States', 'A2', 'AL2', 6, 'All America'),
(19805, 'All Asia', 'China', 'L9', 'AL3', 8, 'All Asia'),
(19806, 'All Africa', 'South Africa', '9A', '99F', 6, 'All Africa'),
(19807, 'Regionalia Mexico', 'Mexico', 'N4', 'J88', 6, 'Regionalia Mexico'),
(19808, 'All Europe', 'United Kingdom', 'N9', 'N99', 5, 'All Europe'),
(19809, 'All Spain', 'Spain', 'N7', 'N77', 5, 'All Spain'),
(19810, 'Regional Air Iceland', 'Iceland', '9N', 'N78', 4, 'Regional Air Iceland'),
(19812, 'Voestar', 'Brazil', '8K', 'K88', 6, 'Voestar Brasil'),
(19813, 'All Colombia', 'Colombia', '7O', '7KK', 6, 'All Colombia'),
(19814, 'Regionalia Uruguay', 'Uruguay', '2X', '2K2', 5, 'Regionalia Uruguay'),
(19815, 'Regionalia Venezuela', 'Venezuela', '9X', '9XX', 6, 'Regionalia Venezuela'),
(19827, 'Regionalia Chile', 'Chile', '9J', 'CR1', 6, 'Regionalia Chile'),
(19828, 'Vuela Cuba', 'Cuba', '6C', '6CC', 5, 'Vuela Cuba'),
(19830, 'All Australia', 'Australia', '88', '8K8', 5, 'All Australia'),
(19831, 'Fly Europa', 'Spain', 'ER', 'RWW', 5, NULL),
(19834, 'FlyPortugal', 'Portugal', 'PO', 'FPT', 5, NULL),
(19886, 'Spring Airlines Japan', 'Japan', 'IJ', 'SJO', 18, NULL),
(19890, 'Dense Airways', 'United States', 'KP', 'DWA', 5, NULL),
(19891, 'Dense Connection', 'United States', 'KZ', 'DC2', 5, NULL),
(19908, 'Vuola Italia', 'Italy', '4S', 'VI4', 5, 'Vuola Italia'),
(19917, 'Jet Suite', 'United States', NULL, 'RSP', 18, NULL),
(19923, 'Fly Jamaica Airways', 'Jamaica', NULL, 'FJM', 6, NULL),
(19927, 'Island Express Air', 'Canada', '1X', NULL, 5, NULL),
(19928, 'All Argentina Express', 'Argentina', 'Z0', 'Z9H', 5, 'All Argentina Express'),
(19930, 'Thai Smile Airways', 'Thailand', 'WE', NULL, 28, 'THAI Smile'),
(19944, 'International AirLink', 'Jamaica', 'I4', NULL, 5, NULL),
(19963, 'Real Tonga', 'Tonga', 'RT', NULL, 3, NULL),
(19970, 'All America AR', 'Argentina', '2R', 'M7A', 5, 'All America Argentina'),
(19971, 'All America CL', 'Chile', '1R', 'R1R', 5, 'All America Chile'),
(19974, 'SOCHI AIR EXPRESS', 'Russia', 'Q4', 'SAE', 8, 'ADLER EXPRESS'),
(19977, 'All America BR', 'Brazil', '1Y', 'A9B', 6, 'All America Brasil'),
(20004, 'Volotea Costa Rica', 'Costa Rica', '9V', 'VC9', 6, 'Volotea Costa Rica'),
(20017, 'Fly Romania', 'Romania', 'X5', 'OTJ', 5, NULL),
(20047, 'Eagle Atlantic Airlines', 'Ghana', 'E2', NULL, 5, NULL),
(20051, 'Fly Africa Zimbabwe', 'Zimbabwe', NULL, 'FZW', 4, 'Zimbabwe flyafrica.com'),
(20060, 'San Dima Air', 'United States', NULL, 'SDI', 3, '(Cyber Airlines) Not Real'),
(20073, 'All America CO', 'Colombia', '0Y', '7ZC', 5, 'All America Colombia'),
(20074, 'All America MX', 'Mexico', '0M', '0MM', 6, 'All America Mexico'),
(20110, 'FOX Linhas Aereas', 'Brazil', 'FX', 'FOX', 12, NULL),
(20127, 'Air Kenya (Priv)', 'Kenya', 'QP', NULL, 6, NULL),
(20144, 'Via Conectia Airlines', 'Uruguay', '6V', 'CZV', 5, 'Via Conectia'),
(20155, 'Hebradran Air Services', 'United Kingdom', NULL, 'HBR', 5, NULL),
(20158, 'Pobeda', 'Russia', NULL, 'PBD', 42, NULL),
(20160, 'City Airways', 'Thailand', 'E8', 'GTA', 8, NULL),
(20170, 'Norwegian Long Haul AS', 'Norway', 'DU', 'NLH', 38, NULL),
(20186, 'BA101', 'United Kingdom', NULL, '710', 4, NULL),
(20207, 'TransNusa Air', 'Indonesia', 'M8', 'TNU', 12, NULL),
(20218, 'Tomp Airlines', 'Chile', 'ZT', 'T9P', 5, 'Tomp Airlines'),
(20220, 'Fuzhou Airlines', 'China', NULL, 'FZA', 32, NULL),
(20221, 'Sky Angkor Airlines (ZA)', 'Cambodia', NULL, 'SWM', 6, NULL),
(20222, 'OneJet', 'United States', 'J1', NULL, 6, NULL),
(20224, 'Global Airlines', 'Argentina', '0G', 'GA0', 5, 'Global Airlines'),
(20225, 'Mann Yadanarpon Airlines', 'Burma', NULL, 'MYP', 6, NULL),
(20264, 'Air Vistara', 'India', 'UK', 'VTI', 52, 'Tata SIA Airlines'),
(20268, 'TransRussiaAirlines', 'Russia', '1E', 'RGG', 8, 'TransRus'),
(20270, 'Severstal Air Company', 'Russia', 'D2', NULL, 8, NULL),
(20282, 'REXAIR VIRTUEL', 'France', 'RR', 'RXR', 4, NULL),
(20285, 'WestJet Encore', 'Canada', 'WR', 'WEN', 48, 'Encore'),
(20286, 'Air Pegasus', 'India', 'OP', 'PPL', 8, NULL),
(20288, 'International Europe', 'Spain', '9I', 'INE', 5, 'International'),
(20293, 'Sky Regional Airlines', 'Canada', NULL, 'SKV', 25, NULL),
(20401, 'V Air', 'Taiwan', 'ZV', 'VAX', 12, 'V Air Taiwan'),
(20415, 'Cello Aviation', 'United Kingdom', NULL, 'CLJ', 8, NULL),
(20478, 'Pouya Air', 'Iran', NULL, 'PYA', 6, NULL),
(20565, 'Boutique Air (Priv)', 'United States', '4B', 'BTQ', 12, NULL),
(20566, 'FlyEgypt', 'Egypt', NULL, 'FEG', 12, 'FlyEgypt'),
(20577, 'VOLOTEA Airways', 'Spain', 'V7', 'VOE', 35, NULL),
(20599, 'INAVIA Internacional', 'Argentina', 'Z5', 'IIR', 5, 'Internacional'),
(20607, 'Liberty Airways', 'United States', 'LE', 'LTY', 5, NULL),
(20608, 'Russian Airline 20608', 'Russia', NULL, NULL, 6, NULL),
(20653, 'Aeronautica Militare', 'Italy', NULL, 'IAM', 125, NULL),
(20657, 'Bassaka airlines', 'Cambodia', '5B', 'BSX', 6, NULL),
(20675, 'Jetstar Japan', 'Japan', NULL, 'JJP', 28, NULL),
(20686, 'SkyBahamas Airlines', 'Bahamas', 'Q7', NULL, 5, NULL),
(20695, 'UVT Aero', 'Russia', 'UW', NULL, 8, NULL),
(20698, 'First Flying', 'Japan', NULL, 'DAK', 6, NULL),
(20710, 'Silver Airways (3M)', 'United States', '3M', NULL, 22, NULL),
(20716, 'AtlasGlobal Ukraine', 'Ukraine', NULL, 'UJX', 8, NULL),
(20725, 'Boliviana de Aviacion (OB)', 'Bolivia', NULL, 'BOV', 14, 'BoA'),
(20726, 'US-Bangla Airlines', 'Bangladesh', NULL, 'UBG', 12, NULL),
(20729, 'Norwegian Air International (D8)', 'Norway', NULL, 'IBK', 32, NULL),
(20752, 'ATA Airlines (Iran)', 'Iran', 'I3', NULL, 12, 'ATA Airlines Iran'),
(20769, 'VIA Lineas Aereas', 'Argentina', 'V1', 'VIA', 6, 'VIA'),
(20802, 'GermanXL', 'Germany', 'GX', 'GXG', 5, NULL),
(20808, 'Alghanim', 'United States', NULL, 'KYA', 4, NULL),
(20824, 'Indonesa Air Aisa X', 'Indonesia', NULL, 'IDX', 12, NULL),
(20827, 'Fly France', 'France', 'FF', 'FRF', 5, 'Fly France'),
(20875, 'Jota Aviation', 'United Kingdom', NULL, 'ENZ', 12, NULL),
(20881, 'Europe Jet', 'France', 'EX', 'EU9', 5, 'Europe Jet'),
(20923, 'COBALT', 'Cyprus', NULL, 'FCB', 6, 'COBALT'),
(20931, 'Southern Airways Express', 'United States', NULL, 'LTD', 28, 'Sun Air Express'),
(20962, 'Orenburzhie', 'Russia', NULL, 'ORG', 8, NULL),
(20976, 'World Scale Airlines', 'United States', 'W3', 'WSS', 5, 'World Scale'),
(20978, 'All America US', 'United States', 'AG', 'SSA', 5, 'All America US'),
(20986, 'University of Birmingham Air Squadron (RAF)', 'United Kingdom', NULL, 'UAY', 8, '8AEF RAF'),
(20991, 'Choice Airways', 'United States', NULL, 'CSX', 5, NULL),
(20994, 'Aruba Airlines', 'Aruba', NULL, 'ARU', 8, NULL),
(20995, 'BudgetAir', 'Germany', '1K', 'BG1', 5, 'BudgetAir'),
(20996, 'Dynamic Airways', 'United States', NULL, 'DYA', 6, NULL),
(21012, 'Fly One', 'Moldova', 'F5', 'FI5', 12, 'Fly One'),
(21021, 'Nordica', 'Estonia', 'EE', NULL, 12, NULL),
(21036, 'Tez Jet Airlines', 'Kyrgyzstan', NULL, 'TEZ', 5, NULL),
(21043, 'Kush Air', 'South Sudan', NULL, 'KUH', 4, NULL),
(21124, 'ViaAir', 'United States', NULL, 'SRY', 8, 'Charter Air Transport'),
(21131, 'All America BOPY', 'Paraguay', '0P', 'PYB', 5, 'All America BOPY'),
(21179, 'Thai Vietjet Air', 'Thailand', NULL, 'TVJ', 18, NULL),
(21248, 'GX Airlines', 'China', NULL, 'CBG', 32, NULL),
(21268, 'Jetgo Australia', 'Australia', 'JG', NULL, 6, NULL),
(21270, 'Air Carnival', 'India', '2S', NULL, 8, NULL),
(21317, 'Svyaz Rossiya', 'Russia', '7R', 'SJM', 22, 'Russian Commuter');